### ISSUE TITLE
Highlighter - and it using for search only for searching the PART with needle words

### ISSUE THREAD

**Issue by lgXenos** [teamtnt/tntsearch#101]
My code:
```
$fullText = 'asd asd asd asd asd asd ad asda das dasd asd adas das da floor, oo.';
$stringPart = $this->tnt->snippet('oo', $fullText, 30);
echo (new TNTSearch())->highlight($stringPart, 'oo', 'b', ['wholeWord'=>false]);
```
What I'm expect? 
`... dasd asd adas das da floor, oo.`

What I'm have?
`...asd asd asd ad asda das...`

Omg... Where is my searching part?

**Comment by lgXenos** [comment]
Code
```$stringPart = $this->tnt->snippet('oo', $fullText, 30, 30);```
Output:
`...das dasd asd adas das da...`

**Comment by nticaric** [comment]
Can you try with a real sentence that makes sense?

**Comment by lgXenos** [comment]
Okay... Look for this... I'm not found defferences between normal text and debug
And second problem: not higlingthing in another case.

![tntsearchnonhigl](https://user-images.githubusercontent.com/14957311/30124272-52d5f17c-933d-11e7-9b83-ab19e715d8a0.png)

My code:
```
	public function getHighlighteringText($length = 300) {
		$fullText   = strip_tags($this->short_text) . strip_tags($this->full_text);
		$stringPart = $this->tnt->snippet($this->searchPhrase, $fullText, $length, $length);

		return $this->tnt->highlight($stringPart, $this->searchPhrase, 'b', [
			'wholeWord' => false,
			'caseSensitive' => false
		]);
	}
```

**Comment by lgXenos** [comment]
Good... Maybe my $length are wrong. And I'm not fully understand sense of second params...
Make some fix: 

> $stringPart = $this->tnt->snippet($this->searchPhrase, $fullText, $length, **round($length/10)** );

![tntsearchnonhigl](https://user-images.githubusercontent.com/14957311/30124719-be685d5c-933e-11e7-8b26-1208dbe4fdc5.png)

Result better, but not good: we stay get empty strings where out text in another case.

![tntsearchnonhigl](https://user-images.githubusercontent.com/14957311/30124769-f33982c2-933e-11e7-8840-b7ac36263d63.png)

**Comment by nticaric** [comment]
wooow, have no idea how to help you, seems you're on your own here :)  maybe the snippet function doesn't work well with cyrillic.

Regarding your test example:

```php

    public function testSnippet()
    {
        $tnt = new TNTSearch;
        $fullText   = 'asd asd asd asd asd asd ad asda das dasd asd adas das da floor, oo.';
        $stringPart = $tnt->snippet('oo', $fullText, 50, 15);
        $this->assertEquals("...dasd asd adas das da floor, oo.", $stringPart);
    }
```

This unit test seems to be passing

**Comment by lgXenos** [comment]
Yours test are passed success
Problem with CaseSen - I'm fix by mbstrtolower only :(

**Comment by lgXenos** [comment]
> wooow, have no idea how to help you, seems you're on your own here :) maybe the snippet function doesn't work well with cyrillic.

Regulars expression must have correct flags and all be good ;)
I saved myself)) 
Any mbstrtolower now!

https://github.com/teamtnt/tntsearch/pull/102

**Comment by nticaric** [comment]
I'm glad for you :)
