### ISSUE TITLE
Fuzzy Search too much "fuzzy"

### ISSUE THREAD

**Issue by Shinseiten** [teamtnt/tntsearch#104]
If I search "gogla" with default fuzzy options, it find "Hero of Goma Fada" as valid.

Goma have the right fuzzy_prefix_length but the wrong fuzzy_distance (is one more), so why its seen as ok? I don't understand. 

name - levenshtein distance
Hero - 5
of - 4
Goma  3
Fada - 4
Hero of Goma Fada - 15

If I set fuzzy_prefix_length=3, it find "Inventor's Goggles".
Same error. Right fuzzy_prefix_length but wrong fuzzy_distance (4 this time).

Am I missing something on how it works?

**Comment by nticaric** [comment]
The levenshtein distance is calculated between stems of the two words, that's why the distance is 2.

This article explains this https://www.elastic.co/blog/found-fuzzy-search

You could create an index without a stemmer and the above effect would be gone

**Comment by Darkinuyasha** [comment]
Thank you, I'll study it.
