### ISSUE TITLE
TNTSearch does not bring results

### ISSUE THREAD

**Issue by 8book** [teamtnt/tntsearch#106]
I installed TNTSearch on my GRAV site, but despite the base being indexed it does not bring the results.

You can see in the following link that it does not even bring the time and the quantity of items.

https://animesonline.top/search
Word Search for search for "Boruto" - "Naruto" - "Dragon Ball"

This same site works perfectly on localhost with apache.
On the production server it is in:
**Vesta Panel**
**Ubuntu 16**
**Nginx + Phpfpm**

When I access the index.grav file through the terminal I can see that everything is indexed. But when we look at the site it does not show the results.

If anyone can help me I'm very grateful!

**Comment by nticaric** [comment]
I guess you should ask here https://github.com/trilbymedia/grav-plugin-tntsearch/issues
