### ISSUE TITLE
(1/1) PDOException SQLSTATE[HY000]: General error: 8 attempt to write a readonly database

### ISSUE THREAD

**Issue by D-sense** [teamtnt/tntsearch#108]
Hello, 

I started getting this error lately in my Laravel app (Ubuntu 16 running on nginx server on DigitalOcean). The error occurs when I post (update/populate) any of my tables. Keep in mind, everything seems fine on my local machine (Mac), but the server.

From my understanding, TNTIndexer.php (precisely, line 88) attempts to write the two index files I created while installing TNTSearch but are denied permission. oK, I give permission and everything seems well. However, when "git push" to the remote server, the permission breaks and I have to do it again manually. This is tedious. Below is the error message I get when I update/post to my tables:

`(1/1) PDOExceptionSQLSTATE[HY000]: General error: 8 attempt to write a readonly database
--
in TNTIndexer.php (line 88)
at PDO->exec('INSERT INTO info ( \'key\', \'value\') values ( \'stemmer\', \'TeamTNT\\TNTSearch\\Stemmer\\PorterStemmer\')')in TNTIndexer.php (line 88)

`
Please, what is the permanent solution to this challenge?
Thank you.

**Comment by stokic** [comment]
This has nothing to do with this specific package, it has to do with the default permissions on your server. It's called umask in Linux, check this link https://docs.oracle.com/cd/E19683-01/817-3814/userconcept-95347/index.html and other on Google how to set default permissions.

Once you set correct umask the problem will be solved permanently :)
