### ISSUE TITLE
Unable to complete install

### ISSUE THREAD

**Issue by boxboi1471** [teamtnt/tntsearch#109]
`/var/www/html/tntsearch$ composer require teamtnt/tntsearch  
Using version ^1.1 for teamtnt/tntsearch
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for teamtnt/tntsearch dev-master -> satisfiable by teamtnt/tntsearch[dev-master].
    - Can only install one of: teamtnt/tntsearch[v1.1.0, dev-master].
    - Installation request for teamtnt/tntsearch ^1.1 -> satisfiable by teamtnt/tntsearch[v1.1.0].

Installation failed, reverting ./composer.json to its original content.`

**Comment by nticaric** [comment]
Can you paste the whole content of your composer.json file. It seems like you're trying to get the dev-master version which doesn't meet your minimum requirements.

Setting `'minimum-stability': dev` would solve the issue for you

**Comment by boxboi1471** [comment]
Here's the contents of the composer.json

`{
    "name": "teamtnt/tntsearch",
    "type": "library",
    "description": "A fully featured full text search engine written in PHP",
    "keywords": [
        "teamtnt", "tntsearch", "search", "fulltext", "geosearch", "fuzzy search"
    ],
    "homepage": "https://github.com/teamtnt/tntsearch",
    "license": "MIT",
    "authors": [
        {
            "name": "Nenad Tičarić",
            "email": "nticaric@gmail.com",
            "homepage": "http://www.tntstudio.us",
            "role": "Developer"
        }
    ],
    "require": {
        "php" : "~5.5|~7.0",
        "ext-pdo_sqlite": "*",
        "ext-sqlite3": "*",
        "ext-mbstring": "*"
    },
    "require-dev": {
        "phpunit/phpunit" : "5.*"
    },
    "autoload": {
        "psr-4": {
            "TeamTNT\\TNTSearch\\": "src"
        },
        "files": [
            "helper/helpers.php"
        ]
    }
}`

**Comment by stokic** [comment]
He meant your composer.json file...

This is a composer.json of the package itself :D

**Comment by boxboi1471** [comment]
Excellent, I ran composer init and added nticaric suggestion for: 

> 'minimum-stability': 'dev'

To complete the install. Now to fumble around and figure how to get it to display. Thank You.
