### ISSUE TITLE
Receiving SQLSTATE[HY000] [2002] No such file or directory when running index command

### ISSUE THREAD

**Issue by justinkazemi** [teamtnt/tntsearch#11]
When I run php artisan index:users, the command throws this error. 

![tntsearch_php_-_riselms_-____documents_development_riselms_](https://cloud.githubusercontent.com/assets/5860879/15485915/d1ed1de0-2107-11e6-8040-8df1a93b8218.png)

However, a file is still generated. 

When I try and use ```TNTSearch::selectIndex("users.index");```
I get a "could not find driver" error.

Could you please help me out?

**Comment by stokic** [comment]
Do you have sqlite driver enabled in your php configuration? Most configurations have it enabled by default...

**Comment by nticaric** [comment]
Check if you have the sqlite extension enabled `php -m | grep sqlite`. I'm assuming your database is MySQL?
