### ISSUE TITLE
isFileSystemIndex() not working

### ISSUE THREAD

**Issue by Findus23** [teamtnt/tntsearch#110]
Hi,

I am trying to implement a search on a website. The content isn't in a database, but a few Markdown files.

The indexing and search works surprisingly easy, but something is confusing me:

https://github.com/teamtnt/tntsearch/blob/master/src/TNTSearch.php#L148

```php
if ($this->isFileSystemIndex()) {
    return $this->filesystemMapIdsToPaths($docs)->toArray();
}
```
Here tntsearch is checking `$this->isFileSystemIndex()` to decide if it should return the ids or the path to the files. (I need the latter)

But the function looks surprisingly unfinished:
https://github.com/teamtnt/tntsearch/blob/master/src/TNTSearch.php#L388

```php
/**
 * @return bool
 */
public function isFileSystemIndex() {
    $this->getValueFromInfoTable('filesystem') == 'filesystem';
}
```
First the key in the database is called `driver` for me:
```
➜  ~/app git:(various-improvements) ✗ sqlite3 tmp/index/docs
SQLite version 3.20.1 2017-08-24 16:21:36
Enter ".help" for usage hints.
sqlite> SELECT * FROM info;
total_documents|0
total_documents|291
driver|filesystem
```

And second the function doesn't return anything.

I have replaced it with this and it seems to be working:

```php
public function isFileSystemIndex()
{
    return $this->getValueFromInfoTable('driver') == 'filesystem';
}
```

Am I missing something or is the file system search not yet finished?

**Comment by nticaric** [comment]
Good catch. The filesystem driver was one of the first features that was implemented but after the code evolved and changed it hasn't been checked anymore, so this seems to be the reason why it's broken. Would it be a problem for you to send a pull request?
