### ISSUE TITLE
Install Issues with ext-pdo_sqlite

### ISSUE THREAD

**Issue by totomtornado** [teamtnt/tntsearch#112]
Problem 1
    - Installation request for teamtnt/tntsearch ^1.1 -> satisfiable by teamtnt/tntsearch[v1.1.0].
    - teamtnt/tntsearch v1.1.0 requires ext-pdo_sqlite * -> the requested PHP extension pdo_sqlite is missing from your system.

I have this installed....

SQLite3 | Scott MacVicar, Ilia Alshanetsky, Brad Dewar
-- | --
SQLite 3.x driver for PDO | Wez Furlong

Is this not correct?

**Comment by stokic** [comment]
well you need to have pdo_sqlite installed and used in your php.ini, could you show your phpinfo output, is there pdo driver listed there?

**Comment by totomtornado** [comment]
I am working on an intranet so I converted it to a pdf here...

To be honest, I am not sure what I am supposed to be installing here...  I ran
`sudo apt-get install php7.0-sqlite3`

Then I uncomment these in my php.ini ... effectively turning it on.... I thought
`extension=php_pdo_sqlite.dll`
`extension=php_sqlite3.dll`

BUT... what am I missing because I still get the error above... I assumed it might be a different name or update that is throwing this off.  Like I installed a later version or perhaps just didn't install it correctly. 
 Do I need an older version of something to make this library work correctly.
[phpinfo().pdf](https://github.com/teamtnt/tntsearch/files/1437801/phpinfo.pdf)

**Comment by nticaric** [comment]
It's important to know that the DLL files are only suitable for windows. If you're running a linux distribution, then the extension is `.so`

The only thing you need to do on linux is to run 
`sudo apt-get install php7.0-sqlite` and after `sudo service apache2 restart``

this is in case you are running apache, and in case fpm run 

`sudo service restart php7.0-fpm`

**Comment by totomtornado** [comment]
ok... that worked... I have to make some files and test it out but it seems to have installed correctly now via composer.

Cheers!!!

**Comment by umerchohan8** [comment]
@nticaric thanks man. You saved my day.

**Comment by techmahedy** [comment]
thanks man. You saved my day.
