### ISSUE TITLE
Best Practice with Multiple Indexes

### ISSUE THREAD

**Issue by totomtornado** [teamtnt/tntsearch#113]
Wow... love how fast this is!!!

One question... 

I am searching titles and I also have some tag words related to the entries.

How should I be searching these?  

1.  Do I have one index by combining via SQL?

2.  Do I have two indexes?  One for titles and one for tag words.... then combine the return arrays in some fashion and get rid of duplicates?

Is there another method?

A suggestion on how to handle this situation would be appreciated.

Thanks for this library... Again... I love the speed!!!

**Comment by stokic** [comment]
In that use case I would suggest having one index where you join all of the data together, seems like the most appropriate way.

If you need a special tag based search then yes, another index would be ok.

In general having two indexes and then matching something isn't the best way to solve things but there might use cases where that's a good way to go

**Comment by totomtornado** [comment]
Thanks... i went with one index!
