### ISSUE TITLE
Create index in existing database 

### ISSUE THREAD

**Issue by marsd** [teamtnt/tntsearch#114]
As such, having the index files will cause access issues with multiple servers. Setting up another Rest API instance as suggested in #72 just to search is not going to be as robust as our load-balanced regular app servers, nor as feasible. Similarly for rsync solutions or network file share.

Would it not be possible to have the index created in an existing MySQL/Postgres db or something like Amazon's RDS?

**Comment by nticaric** [comment]
It would be possible but you'll have to wait for version 2.0 ;)

**Comment by sebastienbarre** [comment]
Was wondering the same actually? Can indexes be stored in an existing MySQL databases?

**Comment by FabricioCabeca** [comment]
I've saw [this fork](https://github.com/sleepless/tntsearch) trying to achieve that, maybe it would be a good starting point for a PR
