### ISSUE TITLE
Paging Suggestions

### ISSUE THREAD

**Issue by totomtornado** [teamtnt/tntsearch#115]
I dont see anything mentioned about paging in the examples.

Is there a way to deal with paging built into the api?

It seems like the search function might be a place you could do this(by passing something instead of 12 in the example below) but It is unclear to me...
$res = $tnt->search("This is a test search", 12);

So something like...this...
$res = $tnt->search("This is a test search", 13-24);
Where 13 is the starting id to return up until 24 

or maybe a third variable to pass to indicate page
$res = $tnt->search("This is a test search", 12, 4);
Here 4 might be the page so it would return ids 37-48

If there is no built-in functionality do you have any suggestions?

**Comment by totomtornado** [comment]
After thinking... I guess I would 

1 set tnt to return 100 ids
2 use my page button click to grab the ids I want (if page two I want ids 12-23... array zero-based and I want twelve records a page)
3 use my sql call to get all the info from record x to record y by passing those ids(12-23)

Right now that is no biggie... just curious on best approach.  Also seems like this would be faster if I could filter out results from tnt first.  Otherwise I am guessing at themax number of records I want returned.

**Comment by nticaric** [comment]
The above mentioned approach is correct, it wouldn't be faster if TNTSearch did this for you because it doesn't matter where you do it

**Comment by totomtornado** [comment]
I guess my concern would be what happens with record sizes bigger than one hundred?  Do I just set tnt to return all the records that match?  If I don't then I can only ever get the 1st hundred records from any search.

to be honest that seems fine for what I am doing currently but it also seems like it is not the correct approach to searching...

**Comment by nticaric** [comment]
By default TNTSearch matches 500 documents, but this can be increased by setting the `maxDocs` variable in TNTSearch class. The 500 documents number is an arbitrary chosen number because the relevancy of documents above that number isn't high anymore. Just like goole, only the first few pages are relevant, others not so much.

**Comment by totomtornado** [comment]
Thanks... will page through sql and manipulation of returned ids fromtnt
then.

Cheers
