### ISSUE TITLE
Ngrams invalid byte sequence for encoding utf8

### ISSUE THREAD

**Issue by fearrr** [teamtnt/tntsearch#116]
When I insert trigrams, I get an error.

PostgreSQL 9.5, Сluster encoding ru_RU.UTF-8

 ```
 [Illuminate\Database\QueryException]
  SQLSTATE[22021]: Character not in repertoire: 7 ERROR:  invalid byte sequence for encoding "UTF8": 0xd0 0x20 (SQL: insert into...

 [PDOException]
  SQLSTATE[22021]: Character not in repertoire: 7 ERROR:  invalid byte sequence for encoding "UTF8": 0xd0 0x20
```

**Comment by nticaric** [comment]
Have you tried running the output of the `buildTrigrams`function through `iconv` respectfully with the charset you need? I guess `0xd0 0x20` is a cyrillic letter that wasn't encoded properly
