### ISSUE TITLE
Combine multiple indexes to one? / Get better search results?

### ISSUE THREAD

**Issue by marleybobby** [teamtnt/tntsearch#117]
Hi,

is it possible to combine two indexes into one? 

I have two models: Movie and Serie. Currently I do a search once in Movie and afterwards in Serie. The problem is now that if I search for series the "correct" result is anywhere below the movie results. 

It seems that there isn't any "weigt / distance" variable after which i could order. So any hints if it's possible to create a single index in the hope that i receive better results, or any other advices?

**Comment by totomtornado** [comment]
I asked about this a few days back... if i understand correctly... it seems you need to adjust the sql statement that builds your index so that it includes all info you want together.

**Comment by totomtornado** [comment]
https://github.com/teamtnt/tntsearch/issues/113

**Comment by nticaric** [comment]
I guess the best solution for you would be to create a faced search, just like amazon. IE if you search for "Jaguar" it will return both cats and cars, then on the left side, you choose your category, ie cars and you'll get only cars returned.

With TNTSearch you can achieve this with two indexes, and after the user selects his facet, you only query this one index.

**Comment by marleybobby** [comment]
@nticaric  Think i will go with the faceted search. I really miss a weight/relevance attribute, so could could sort it after that and drop unnecessary entries. 

@totomtornado I don't really have a clu how to create one index with laravel scout :/
