### ISSUE TITLE
Processed x rows Total rows y in output if created via http api 

### ISSUE THREAD

**Issue by marleybobby** [teamtnt/tntsearch#122]
I'm using TNTSearch in combination with Laravel. So far it works great. 

I wrote a api where I fetch data from external services and create a post based on the information. I will insert then some other information which where send with the request. 

Now I saw that the ouput contains "strange" output.  "Processed x rows"  "Total rows y".
Why does this happen?  Does TntSearch in combination with Laravel runs through every entry if a post is created? 

How can I get rid of it?

**Comment by ultrono** [comment]
The output is coming from https://github.com/teamtnt/tntsearch/blob/master/src/Indexer/TNTIndexer.php#L274

This calls a function called ```info()``` at https://github.com/teamtnt/tntsearch/blob/master/src/Indexer/TNTIndexer.php#L632

If you look at the class you can see the function checks a variable called ```$disableOutput``` before outputting the message.

**Comment by marleybobby** [comment]
and how can i disable it?

**Comment by ultrono** [comment]
```$disableOutput``` is a public variable so you can change it directly.

**Comment by ultrono** [comment]
@marleybobby I've just had a go of this myself. 

You need to set the variable on the ```TNTSearch``` instance, as after calling ```createIndex```  an instance of ```TNTIndexer``` is returned, that has the variable in question. i.e.

```
$tnt = new TNTSearch;
$indexer = $tnt->createIndex('orders.index');
$indexer->disableOutput = true;
```

**Comment by ultrono** [comment]
@marleybobby Ha, it's also demonstrated in the tests, which I should have looked at initially :) See https://github.com/teamtnt/tntsearch/blob/master/tests/TNTSearchTest.php#L47-L48

**Comment by marleybobby** [comment]
Will take a look how to achieve this with laravel as framework. Thanks for you answer :)  Will keep it updated if I find a way to do it in laravel.

**Comment by ultrono** [comment]
Well as this repo isn't for the Laravel Scout driver, my answer only applies to this repo. I've had a quick look at the import command in the Scout driver repo and cannot see any obvious place to disable output.

**Comment by nticaric** [comment]
@ultrono feel free to submit a PR to the tntsearch scout repo with a setter method that would disable the output

**Comment by ultrono** [comment]
@nticaric I think it was @marleybobby who wanted that functionality. Personally I prefer to see the output I find it useful :)

**Comment by nticaric** [comment]
@ultrono sorry :)
