### ISSUE TITLE
Inserting a 4Kb text takes forever

### ISSUE THREAD

**Issue by pgordinho** [teamtnt/tntsearch#125]
Hi,

Just started using TNTseach and found it very useful and easy to setup. Created my index in minutes and without a problem and started searching:

```
$indexer = $tnt->createIndex('data.index');
$indexer->query('SELECT id, name, other_names, country, state, city, interest, transfer, description, source FROM canyons;');
$indexer->run();
```

Indexing takes about 1s with 55 rows, but now I want to insert into the index as soon as the user inserts more data, so...

```
$tnt->selectIndex("data.index");
$index = $tnt->getIndex();
$index->insert([
    'id' => $lastInsertId, 
    'name' => 'teste', 
    'other_names' => 'more names',
    'country' => 'Portugal',
    'state' =>  'Aveiro',
    'city' => 'Aveiro',
    'interest' => '4',
    'transfer' => 'Carro',
    'description' => $_POST['description'],
    'source' => ''
    ]);

```
I've attached contentes of $_POST['description']. It's about 4Kb
[description.txt](https://github.com/teamtnt/tntsearch/files/1673658/description.txt)
 
Updating the index will take forever. I can hear the disk working while it tries to insert, but I'll get a timeout meanwhile.

Any help?

**Comment by nticaric** [comment]
Hmm, this is strange, because 4kb of data should be processed in milliseconds.

What about this approach, is it faster?

```php

$tnt->selectIndex("data.index");
$index = $tnt->getIndex();
$index->indexBeginTransaction();
$index->insert([
    'id'          => $lastInsertId,
    'name'        => 'teste',
    'other_names' => 'more names',
    'country'     => 'Portugal',
    'state'       => 'Aveiro',
    'city'        => 'Aveiro',
    'interest'    => '4',
    'transfer'    => 'Carro',
    'description' => $_POST['description'],
    'source'      => '',
]);

$index->indexEndTransaction();
```

**Comment by pgordinho** [comment]
Perfect! With BeginTransaction and EndTransaction between the insert works flawlessly. Like you said... miliseconds!

**Comment by michaelrog** [comment]
I'm starting to dig into TNT and learning my way around the project. Where could I look for docs/explanation about how `indexBeginTransaction` and `indexEndTransaction` make this so much more performant?

**Comment by nagi1** [comment]
Hey @michaelrog, 
It been a long time I know but I love this package and I want to learn more about how it works under the hood.
I'm wondering if you have access to any doc/educational recourse for this piece of art?
