### ISSUE TITLE
Order by relevance

### ISSUE THREAD

**Issue by drewdeakin** [teamtnt/tntsearch#127]
Is it possible to order the results by relevance?

Single word searches are okay, (ie searching for "balance", brings up any thing with "balance")

But when you start using 2 or more words (ie "balance naturals"), I'm getting results with either "balance", "naturals" and "balance naturals".

The code I am using is below;

```
$tnt->selectIndex( "products.index" );
$tnt->asYouType = true;

$res = $tnt->search( $_GET['query'], 120 );
$res = implode( ',', $res['ids'] );
```

**Comment by stokic** [comment]
The whole point of the full-text search is that the results are already ranked by relevance. Otherwise, it wouldn't make much sense, would it? :)

What you need is Boolean search https://github.com/teamtnt/tntsearch#boolean-search

**Comment by renanvalente** [comment]
And if I want to change relevance, add new criteria.

It's possible?

**Comment by nticaric** [comment]
@renanvalente TNTSearch returns a list of ids containing your search query. What you can do is
to add an oder criterion in your query. ie date

SELECT * FROM articles WHERE id IN $res ORDER BY date;
