### ISSUE TITLE
Updating the index (automatically), not working?

### ISSUE THREAD

**Issue by shacall2** [teamtnt/tntsearch#13]
I'm having issues getting the index to automatically update.  I followed the instructions outlined here:

http://tnt.studio/blog/searching-for-bobby-fisher-with-laravel-5

I added all 4 of the static functions to my model (I'm assuming the boot method is in the same model?).  When I insert a new record into my database (using the DB facade), nothing seems to get indexed.  Search never finds these new records, unless I manually run:  php artisan <model>.index.

At this point, I'm not sure if it's a bug…or if I added the boot method to the wrong model…or if it's something else.  Any help would be much appreciated!

I'm very happy with this package!

**Comment by nticaric** [comment]
The `DB` facade doesn't trigger the created, updated and deleted events. In order to do that you need to use the model like:

```php
$model = new Model;
$model->title = "Something";
$model->save();
```

The `->save()` method will now trigger an according event. Or if you want to do it manualy:

```php
$tnt->selectIndex("name.index");
$index = $tnt->getIndex();
//to insert a new document to the index
$index->insert(['id' => '11', 'title' => 'new title', 'article' => 'new article']);
```
