### ISSUE TITLE
Disregard search for certain HTML tag options

### ISSUE THREAD

**Issue by renanvalente** [teamtnt/tntsearch#131]
Possible to inform that in certain options of HTML tags TNTSearch should not return as a result.

Example: 
I would not like to receive the content below as a result of a search for "name" or "image", only if I searched for "example" or "text"
`<p>Example text <img src="image_name.jpg" /></p>`

**Comment by nticaric** [comment]
In this case you should either write your own tokenizer that would strip tags or either use the stopword option to remove the tags from index.
