### ISSUE TITLE
Problem with using Geo Search

### ISSUE THREAD

**Issue by BalakovoSpace** [teamtnt/tntsearch#137]
For generate Geo Search index i using string from examples:
```php
use TeamTNT\TNTSearch\TNTSearch;
$candyShopIndexer = new TNTGeoIndexer;
```
But PHP generate fatal error:

> Uncaught Error: Class 'TNTGeoIndexer' not found in ...

But all classes included and normal search / indexer work correctly.

Howto using Geo Search correctly?

**Comment by ultrono** [comment]
Please read the documentation and refer to the PHP manual. This is VERY clearly stated within the repository read me at https://github.com/teamtnt/tntsearch#geo-search. 

I'd recommend reading about namespaces. You've imported the ```TNTSearch``` class but not the ```TNTGeoIndexer``` class - this is what the error message is saying.

**Comment by BalakovoSpace** [comment]
Thank you.
Sorry for the stupid question.
