### ISSUE TITLE
Search not returning id for phrases present in db

### ISSUE THREAD

**Issue by michaeldim** [teamtnt/tntsearch#14]
Hi,

I have found an issue when using the search/searchBoolean method where the phrase being searched was returning no ids despite the phrase being present in my db.

To replicate, please insert the following rows into the articles db with tests:

```
id | title  | article
11 | Eldred | What the foo
12 | Eldred | Oh my bar
```
Then add these assertions and run phpunit.

```
$res = $tnt->searchBoolean('eldred -bar');
$this->assertEquals([11], $res['ids']);

$res = $tnt->searchBoolean('Eldred -bar');
$this->assertEquals([11], $res['ids']);
```

The second assertion will fail.  It appears linked to the phrase being used in addition to that phrase starting with a capital letter.  I have managed to get around this issue by using strtolower.

**Comment by nticaric** [comment]
Nice catch! Thanks for spotting it. It fixed in v0.6.2
