### ISSUE TITLE
 PDOException: could not find driver in /var/www/app/vendor/teamtnt/tntsearch/src/TNTSearch.php:88

### ISSUE THREAD

**Issue by wagneralkmim** [teamtnt/tntsearch#140]
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/pdo_sqlite.so' - Error relocating /usr/lib/php7/modules/pdo_sqlite.so: zend_empty_string: symbol not found in Unknown on line 0

**Comment by ultrono** [comment]
Please read the repository readme. 

As per the requirments at https://github.com/teamtnt/tntsearch#requirements you need the SQLite PHP Extension

**Comment by wagneralkmim** [comment]
How I install SQLite PHP Extension using Ambientum on Ubuntu? TNTSearch been working until yesterday. Today after I run docker-compose --build --force-recreate it stopped working.

**Comment by ultrono** [comment]
That's a little out of the scope of what support to expect from the package or a Github issue page. It appears some PHP settings were lost when you rebuilt your container.

This is not a TNTSearch issue.

**Comment by wagneralkmim** [comment]
Ok, But thanks!
