### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by moerphie** [teamtnt/tntsearch#141]
Hello,
is it possible to refine the fulltext search with some simple select request?

For example:

Index
```php
$index->insert([	'id' => '1', 
			'title' => 'new title', 
			'article' => 'new article', 
			'category' => 'post', 
			'date' => 20180101, 
			'comments' => 99]);
```

Query
```php
$res = $tnt->searchBoolean('(romeo or hamlet) -juliet');
$res = $res->select('category', 'equal', 'post');
$res = $res->select('date', 'greaterthan', 20181212);
$res = $res->select('comments', 'lessthan', 10);
```

**Comment by ultrono** [comment]
You'd really need to do that after the search. i.e. get the results as normal from TNT and then filter the results by category, comments etc. 

If you use the Laravel specific driver you can add such constraints easily on the query. i.e. 

```$orders = App\Order::search('Something cool')->where('user_id', 1)->get();```

If not using Laravel you'd need to filter your result. i.e. on the ```$res``` variable within the examples at https://github.com/teamtnt/tntsearch#searching

**Comment by ultrono** [comment]
Also remember that when building your index, the title can be a combination of fields.
