### ISSUE TITLE
Reuse existing PDO connection

### ISSUE THREAD

**Issue by rkyoku** [teamtnt/tntsearch#142]
Hi there,

Would it be possible to reuse an existing PDO connection when building/updating the indexes?

It would save another (costly) connection, for each user performing a search. Depending on the website/application, it may be of importance, and I imagine it would be quite easy to implement?

What do you think?

**Comment by nticaric** [comment]
I guess the PDO connection could be created with `PDO::ATTR_PERSISTENT => TRUE` but this has also its downsides.

On the other hand, most users use either apache or nginx and they persist the database connection per thread. 
This means if lets say 1000 users come to your site, there won't be 1000 connections open,
but only a small amount, depending on how many thready your server is running.

**Comment by rkyoku** [comment]
> most users use either apache or nginx and they persist the database connection

Sorry, I was not aware of that. I never did that, and nobody did that in my previous jobs either. Maybe you're right and that's what all people do, I'm just stating my experience, and that I may totally be mistaken.

If you think nobody will benefit from passing in the PDO connection when initializing TntSearch, then feel free to close this ticket. I just thought it could be useful to people, that's all :)

Thanks for your comment @nticaric !
