### ISSUE TITLE
Fuzzy search not behaving like expected (stuido vs dowlnoad)

### ISSUE THREAD

**Issue by rkyoku** [teamtnt/tntsearch#146]
Hi there,

I mispelled two terms on purpose (`studio` => `stuido`, and `download` => `dowlnoad`), and I get different results.

Here is my test code:
```
$this->_tnt->fuzziness = true;
$this->_tnt->fuzzy_prefix_length = 1;
$aRes = $this->_tnt->getWordlistByKeyword($sTerm, false);
```

For `stuido` I get an empty result :'( (although the word `studio` is indeed indexed, I checked)

For `dowlnoad` I get a single result: `download`, as expected.

Why is it not working for `stuido` whereas it works for `dowlnoad`? Am I doing something wrong?

I am just calling this one method: `getWordlistByKeyword`, that's all. I'm not performing a search.

Thanks guys!

Cheers,

**Appendix:**

`SELECT * FROM wordlist WHERE term like "stud%" ORDER BY num_hits DESC`

```
Array
(
    [0] => Array
        (
            [id] => 60
            [term] => study
            [num_hits] => 23
            [num_docs] => 21
        )

    [1] => Array
        (
            [id] => 4916
            [term] => studio
            [num_hits] => 16
            [num_docs] => 5
        )

    [2] => Array
        (
            [id] => 1371
            [term] => students
            [num_hits] => 8
            [num_docs] => 7
        )

    [3] => Array
        (
            [id] => 4917
            [term] => studios
            [num_hits] => 7
            [num_docs] => 2
        )

    [4] => Array
        (
            [id] => 98
            [term] => studies
            [num_hits] => 4
            [num_docs] => 4
        )

    [5] => Array
        (
            [id] => 2297
            [term] => student
            [num_hits] => 3
            [num_docs] => 3
        )

    [6] => Array
        (
            [id] => 2449
            [term] => studied
            [num_hits] => 3
            [num_docs] => 3
        )

    [7] => Array
        (
            [id] => 6687
            [term] => studying
            [num_hits] => 1
            [num_docs] => 1
        )
)
```

**Comment by nticaric** [comment]
I would guess that your `fuzzy_max_expansions` property is set to a low number in respect to `fuzzy_prefix_length `. 
To give you a better understanding lets say you have 1000 words that start with  the letter `s`. If the `fuzzy_max_expansions` is kept at its default value you will only get 50 results starting with letter `s` if you used `fuzzy_prefix_length = 1;`

In your particular case you should change the `fuzzy_prefix_length`  to 3 and `fuzzy_max_expansions`to let's say 100


The fuzziness only seems like magic :) but what it actually does is it will do a query  like
`SELECT * FROM wordlist WHERE term like 'stu%' ORDER BY num_hits DESC LIMIT {$this->fuzzy_max_expansions}` and than calculate the Levenshtein distance for each of those results with your query and return the best match.

This part `'stu%' ` in the query represents `fuzzy_prefix_length`. So in case

fuzzy_prefix_length = 1 it becomes `'s%'

fuzzy_prefix_length = 2 it becomes `'st%'

fuzzy_prefix_length = 3 it becomes `'stu%'
etc.
