### ISSUE TITLE
japanese support

### ISSUE THREAD

**Issue by amnek0** [teamtnt/tntsearch#147]
does it support Japanese? The index is easily created but a search returns nothing, and i'm sure "あいたい" is in the database.

```
require_once 'vendor/autoload.php';

use TeamTNT\TNTSearch\TNTSearch;

$tnt = new TNTSearch;

$tnt->loadConfig([
    'driver'    => 'mysql',
    'host'      => 'localhost',
    'database'  => 'lovejp',
    'username'  => 'neko',
    'password'  => 'abc0987',
    'storage'   => __DIR__.'/oyasumi/'
]);

$tnt->selectIndex('name.index');

$res = $tnt->search('あいたい', 7);
```

```
Array
(
    [ids] => Array
        (
        )

    [hits] => 0
    [execution_time] => 1.0719 ms
)

```

**Comment by amnek0** [comment]
same, no results.

**Comment by nticaric** [comment]
Not sure if the tokenizer breaks the japanese text correctly. Can you try to run the text through this method

```php
    public function tokenize($text, $stopwords = [])
    {
        $text  = mb_strtolower($text);
        $split = preg_split("/[^\p{L}\p{N}]+/u", $text, -1, PREG_SPLIT_NO_EMPTY);
        return array_diff($split, $stopwords);
    }
```

and let us know what you get

**Comment by amnek0** [comment]
```
Array
(
    [0] => あいたい
)

```

**Comment by nticaric** [comment]
Thanks. It seems like the tokenizer doesn't break this into single words. I guess you could write a tokenizer that breaks the text correctly

**Comment by amnek0** [comment]
Yes, I tried another database with English words, and it worked, I'm sure there is something wrong with Japanese.

for the word "あいたい", shouldn't it give me one result as "あいたい"? It's the same in the database.

**Comment by nticaric** [comment]
I guess the indexer doesn't store it as one word in the index, since the tokenizer doesn't work correctly for Japanese. Since I don't know Japanese at all, I'm not able to help, but someone could write a correct tokenzier function that would break a sentence into single words

```php
   public function tokenize($text, $stopwords = [])
    {
        $text  = mb_strtolower($text);
        $split = splittin_japanese_text_into_single_words($text);
        return array_diff($split, $stopwords);
    }
```

**Comment by amnek0** [comment]
Can't find anything better than tnt, i got an idea, if every row is a single word, then no need for tokenizer, is it possible? what should I edit? The table is just a large list of vocabularies(with duplicates).
