### ISSUE TITLE
filesystem driver: do not index path and/or filename

### ISSUE THREAD

**Issue by Connum** [teamtnt/tntsearch#150]
I'm using the filesystem driver to index a large number of HTML files. Inspecting the index database, I've seen that the full file path is also being indexed. My files are fore example located in C:\xampp\htdocs\someapp\items\

The indexer adds "d", "xampp", "htdoc", "someapp", "item" for each and every page. What I would like to do is exclude the path from being indexed.

Is there already an option that I have missed, or would I have to extend the filesystem-based indexing in order to achieve this? If so, I'd be happy to share this with a PR.

**Comment by nticaric** [comment]
Currently, there is no option to exclude the filename. We'd be glad to accept the PR if you add the functionality. Maybe adding a boolean property called `excludeFileNameFromIndex` and then doing something like 

```php
if($this->exludeFileNameFromIndex) {
    unset($file['name'])
}
```

**Comment by Connum** [comment]
I think I have an even more flexible solution! Adding 
```
public $fileMapCallback = null;
public $fileFilterCallback = null;
```
to the `TextFileReader` and using
```
$fileCollection = new Collection($file);

if (is_callable($this->filereader->fileFilterCallback)) {
    $fileCollection = $fileCollection->filter($this->filereader->fileFilterCallback);
}
if (is_callable($this->filereader->fileMapCallback)) {
    $fileCollection->map($this->filereader->fileMapCallback);
}

$this->processDocument($fileCollection);
```
in `TNTIndexer`, opens up a whole new world of possibilities in terms of influencing what is being indexed and how. For example, to remove the name key completely, thus stopping the path from being indexed, you could use this:
```
$fileReader = new TeamTNT\TNTSearch\FileReaders\TextFileReader;
$fileReader->fileFilterCallback = function($value, $key) {
	return $key != 'name';
};
$indexer->setFileReader($fileReader);
```

Or if you'd only like to index the base folder name without the whole path to it, you could just do:
```
$fileReader = new TeamTNT\TNTSearch\FileReaders\TextFileReader;
$fileReader->fileMapCallback = function($value, $key) {
	if ($key == 'name') {
		return basename(dirname($value));
	}

	return $value;
};
$indexer->setFileReader($fileReader);
```
Likewise you could set the `id` to a key that's provided in the path/foldername/filename (just should make sure that it's unique in that case).

Let me know what you think!

**Comment by nticaric** [comment]
Sounds great! Please submit a PR and I'l merge it

**Comment by persianphilosopher** [comment]
Apologies for commenting on a closed issue but that is very much a problem I have faced and it would be really helpful if you could give us a snippet of how to implement this PR. Thanks a million

**Comment by Connum** [comment]
Hi @persianphilosopher,
the last two code sections in my comment https://github.com/teamtnt/tntsearch/issues/150#issuecomment-394092694 explain how to use the code. If you tell me what exactly isn't clear, I'll try to explain as good as I can.
