### ISSUE TITLE
polish characetrs

### ISSUE THREAD

**Issue by MrBlueBird** [teamtnt/tntsearch#156]
Does tntsearch support Polish characters?

How to make the "ogród" be the same as "ogrod"

**Comment by naptalky** [comment]
Hello MrBlueBird,
Took me a while but I figured out how to search with Polish characters.

You have to set `'charset'	=> 'utf8'` in your `loadConfig()` method.
The config could look like this:
```
$tnt = new TNTSearch;

$tnt->loadConfig([
    'driver'    => 'mysql',
    'host'      => 'db_host',
    'database'  => 'db_name',
    'username'  => 'db_username',
    'password'  => 'db_password',
    'storage'   => './storageFolder/',
    'charset'	=> 'utf8'
]);
```

Hope I helped you!
