### ISSUE TITLE
Update Document Indexed by TNTGeoIndexer Not Possible?

### ISSUE THREAD

**Issue by ge022** [teamtnt/tntsearch#158]
I see that TNTGeoIndexer does not create some tables such as 'doclist' and 'wordlist', which is required in the update methods. Is there any way to update documents indexed by TNTGeoIndexer?

**Comment by mohammedalik** [comment]
me also required this answer...help me

**Comment by nticaric** [comment]
With version v2.1.0 you can do the following:

```php
$geo = new TNTGeoSearch();
$geo->loadConfig([
    'storage'   => storage_path()
]);
$geo->selectIndex('name.index');
$index = $geo->getIndex();

$index->insert(['id' => $id, 'latitude'=> $lat,'longitude'=> $long]);

```
