### ISSUE TITLE
Web crawler and auto index

### ISSUE THREAD

**Issue by bs-thomas** [teamtnt/tntsearch#165]
Hello there,

I've looked at your getting started guide, and noticed that the first thing is to connect with the Database, and assume that it's indexing the columns in an existing database.

Referencing swiftype, a paid (expensive) Elastic Search service, they have this web crawler that crawls along your websites and indexing all pages it finds (including the static pages not stored in the database).

I was wondering if you have some sort of similar feature or option.

Thank you very much!

**Comment by nticaric** [comment]
I guess a solution for you would be to fetch the webpage with file_get_contest and save it to disk, and then using the filesystem driver
