### ISSUE TITLE
Call to a member function stem() on null

### ISSUE THREAD

**Issue by naptalky** [teamtnt/tntsearch#169]
Windows 10 x64, XAMPP with PHP7.

Hello, starting my adventure with TNTSearch I encountered a problem.
When I try (following your docs) `$tnt->search("search term", 12);` it returns me following error:

> Fatal error: Uncaught Error: Call to a member function stem() on null in C:\xampp\htdocs\_LIBS\tntsearch\vendor\teamtnt\tntsearch\src\TNTSearch.php:108 Stack trace: #0 [internal function]: TeamTNT\TNTSearch\TNTSearch->TeamTNT\TNTSearch\{closure}('optics', 0) #1 C:\xampp\htdocs\_LIBS\tntsearch\vendor\teamtnt\tntsearch\src\Support\Collection.php(78): array_map(Object(Closure), Array, Array) #2 C:\xampp\htdocs\_LIBS\tntsearch\vendor\teamtnt\tntsearch\src\TNTSearch.php(109): TeamTNT\TNTSearch\Support\Collection->map(Object(Closure)) #3 C:\xampp\htdocs\_LIBS\tntsearch\index.php(50): TeamTNT\TNTSearch\TNTSearch->search('optics', 12) #4 {main} thrown in C:\xampp\htdocs\_LIBS\tntsearch\vendor\teamtnt\tntsearch\src\TNTSearch.php on line 108

I found an issue #64 with exactly the same problem, but the answer is "Oops. just a bad call". Bad practice because I have the same issue and dont have an answer.

I am using TNTSearch without any framework, just a single php file connected to a mysql database (outside).
```
<?php
require_once __DIR__ . '/vendor/autoload.php';
use \TeamTNT\TNTSearch\TNTSearch;

$tnt = new TNTSearch;

$tnt->loadConfig([
    'driver'    => 'mysql',
    'host'      => 'myhost.domain',
    'database'  => 'mydb.name',
    'username'  => 'mydbuser',
    'password'  => 'mydbuserpassword',
    'storage'   => './tntdb/'
]);
$res = $tnt->search("optics", 12);
print_r($res);
?>
```

Edit: What's more, I successfully did indexing, indexed 1400 rows in total and the name.index file appeared with some kb's of size so I suppose it's configured fine.

**Comment by nticaric** [comment]
It seems like you are missing this line

$tnt->selectIndex("name.index");

**Comment by naptalky** [comment]
That's exactly right sir, my bad. I've already tested tntSearch and it's really promising- fast, functional and flexible.

(To future visitors)
The proper first-search-code should look like this:
`<?php
// require composer autoload - required to find your TNTSearch package
require_once __DIR__ . '/vendor/autoload.php';
use \TeamTNT\TNTSearch\TNTSearch;

// new TNTSearch object
$tnt = new TNTSearch;

// configure connection to "mother" database
$tnt->loadConfig([
    'driver'    => 'mysql',
    'host'      => 'myhost.domain',
    'database'  => 'mydb.name',
    'username'  => 'mydbuser',
    'password'  => 'mydbuserpassword',
    'storage'   => './tntdb/'
]);

// creating index and indexing columns [id, company name, address, city]
$indexer = $tnt->createIndex('name.index');
$indexer->query('SELECT id,d_company,d_address,d_city FROM company');

// is this for fuzziness purposes?
//$indexer->setLanguage('german');

// run indexer
$indexer->run();

// select index and search for "optics", limit results to 12
$tnt->selectIndex("name.index");
$res = $tnt->search("optics", 12);

// print out our results
print_r($res);
?>`

Hope this helps someone!
