### ISSUE TITLE
Tutorial request

### ISSUE THREAD

**Issue by Nwabueze** [teamtnt/tntsearch#172]
This project sounds too good but the tutorials here are not really enough to supercharge people, on the fly, who came here through  search. I am simply appealling to the awesome contributors to consider this point.
In particular, the text classifier training axamples proceeded by supplying a text and corresponding label one at a time. HOW CAN WE DO THIS ONCE BY SUPPLYING ARRAY. like: train([x1->y1,x2->y2,x3->y3])

**Comment by ultrono** [comment]
What's wrong with https://github.com/teamtnt/tntsearch#tutorials - personally found them quite in depth. However, would agree that some features are lacking in tutorials.

**Comment by Nwabueze** [comment]
From my use case, if I have 1k features & 
labels, obviously I wont do:
... learn(x1,y1)
... learn(x2,y2)
... learn(x1000,y1000)
I'd have to either supply array of features to train: list=[x1,y1... x1000,y1000] once.
How can we do this.
is it possible to do the following
for: (items in list learn(x,y)

**Comment by nticaric** [comment]
Yeah, a for loop would be possible 

$classifier = new TNTClassifier();

```php
foreach($youreArrayOfItems as $item) {
    $classifier->learn($item->description, $item->category);
}
```

Also, take a look at the unit tests for the classifier. There we're classifying around 5k SMS messages
into SPAM and HAM. 80% of the dataset is used for training and 20% for evaluation

https://github.com/teamtnt/tntsearch/blob/master/tests/classifier/TNTClassifierTest.php#L16

And here's a tutorial for you :)

https://medium.com/@nticaric/text-classification-with-php-7c571527e28c

**Comment by nticaric** [comment]
About speech tagging, this wouldn't be possible with this classifier, since its naive bayes. Hidden Markov models would be more suitable for this
