### ISSUE TITLE
Speed up the search

### ISSUE THREAD

**Issue by alkhachatryan** [teamtnt/tntsearch#175]
Hi. I have imported ~ million record into tntsearch storage. Now the search is getting more then 10s to show results. How can I speed up?

PS I have a server with 18 Cores and 64GB RAM and I'm testing there

I'm using:

- Laravel 5.7

- laravel-scout-tntsearch-driver 3.2

Here is my configs
` 'tntsearch' => [
        'storage'  => storage_path() . '/tntsearch', //place where the index files will be stored
        'fuzziness' => env('TNTSEARCH_FUZZINESS', true),
        'fuzzy' => [
            'prefix_length' => 2,
            'max_expansions' => 50,
            'distance' => 3
        ],
        'asYouType' => true,
        'searchBoolean' => env('TNTSEARCH_BOOLEAN', false),
    ], `

**Comment by alkhachatryan** [comment]
Will try, thank

**Comment by alkhachatryan** [comment]
I tried it and it didn't help. I switched to Postgre Searchable fulltext. Becase to show the results from it is getting 7-8s (2s faster then TNTSearch)

**Comment by stokic** [comment]
hm can you show your table design? something is very strange if both engines are relatively slow. I would guess that you have some large field like blob or similar which is indexed and shouldn't be...
