### ISSUE TITLE
No search results on Cloud Server

### ISSUE THREAD

**Issue by ngongcm** [teamtnt/tntsearch#18]
First I will like to say this is an amazing search extension! However, I having issues getting this to work on my digitalocean cloud server with laravel forge. The extension works perfectly on my local server (Homestead / vagrant) but onces I upload everything to the cloud, it shows no result.

**here is var_dump of my local server Homestead:**

**And here is var_dump of my digitalocean server:**

Here is a var_dump of my code section:

Somehow it seems not pass in the results from $tnt on my cloud side.. Please let me know if I'm doing anything wrong here. My guess is that this is a server configuration issue since it's working fine on my local server.

**Comment by nticaric** [comment]
Can you `var_dump($res)` instead of `$tnt`. And also make sure that the folder `/home/forge/trendingquestions.com/storage/` is writable. Also don't forget to run the indexer first

**Comment by ngongcm** [comment]
Thanks for the prompt respond. Here is my var_dump($res) for both local and cloud

local
![screen shot 2016-06-15 at 3 03 45 pm](https://cloud.githubusercontent.com/assets/19656779/16093626/9d4009f8-330a-11e6-858f-62ea21dcf5f1.png)

Cloud
![screen shot 2016-06-15 at 3 03 34 pm](https://cloud.githubusercontent.com/assets/19656779/16093634/a35c7e8e-330a-11e6-8720-eeef7e5e5223.png)

Also i have ran the index in both servers and the index file has been created in the storage folder in both servers. So this let me believe that this might be a permission issue? I am new to ubuntu and really don't know how to make sure that the permission is correct in the storage folder. So if you can please help me with this then that will be awesome. If you think the issue is something else the please let me know.

**Comment by nticaric** [comment]
just for testing purposes you can run `chmod -R 0777 /home/forge/trendingquestions.com/storage/`
but could it also be that your database is empty?

**Comment by ngongcm** [comment]
Still the same lol.... Database on cloud has content and the generated index file also has content just like the one on my local server...

**Comment by ngongcm** [comment]
Also I found a difference in the folder and file permission on both servers. Take a look below:

Local
![screen shot 2016-06-15 at 5 27 09 pm](https://cloud.githubusercontent.com/assets/19656779/16097937/96310fea-331e-11e6-9365-28d01ec5787a.png)

Cloud
![screen shot 2016-06-15 at 5 26 51 pm](https://cloud.githubusercontent.com/assets/19656779/16097942/9b77762e-331e-11e6-9916-9df4b7f73bb7.png)

As you can see access to local **Access: 2016-06-15 19:01:46.000000000 +0000**
While access to the cloud is this: **Access: 2016-06-15 17:13:39.845439921 -0400**

Could this be the problem?

**Comment by ngongcm** [comment]
After looking at this closely i think my issue starts from the $tnt->selectIndex("questions.index"); not accessing the index file on my cloud server. Since there is no result when I var_dump it. Any reason why this is happening?

**Comment by nticaric** [comment]
I think you would get an exception thrown if the index file wasn't accessible. Could you try with `$tnt->search()` method instead of `$tnt->searchBoolean()` since it's not so strict
