### ISSUE TITLE
How to add a new record to existing geoindex.... Hi help me pls....

### ISSUE THREAD

**Issue by mohammedalik** [teamtnt/tntsearch#184]

**Comment by mohammedalik** [comment]
How to add a new record to existing geoindex....

     $candyShopIndex = new TNTGeoSearch();
                $candyShopIndex->loadConfig([
                        'driver'    => env('DB_CONNECTION'),
                        'host'      => env('DB_HOST'),
                        'database'  => env('DB_DATABASE'),
                        'username'  => env('DB_USERNAME'),
                        'password'  => env('DB_PASSWORD'),
                        'storage'   => storage_path(),//'/swapLocation.index',
                    ]);
                $candyShopIndex->selectIndex('swapdistance.index');
                 $candyShopIndex->insert(['id' => $id, 'latitude'=> $lat,'longitude'=> $long,]);


not working

**Comment by mohammedalik** [comment]
hi tntteam, help me pls...
i m in trouble ...
i m unable add new record geo index...
give me a simple code...

**Comment by mohammedalik** [comment]
Help me pls...

**Comment by mohammedalik** [comment]
i m in project to finish ....
because of this problem i stucked...
how to add a row in geoloaction index in tnt...
in documentation its not there...
everything is working for me...
only this is requered....

**Comment by nticaric** [comment]
What you can do is update TNTSearch to v2.1.0 and after that run:

```php
$geo = new TNTGeoSearch();
$geo->loadConfig([
    'storage'   => storage_path(),//'/swapLocation.index',
]);
$geo->selectIndex('swapdistance.index');
$index = $geo->getIndex();

$index->insert(['id' => $id, 'latitude'=> $lat,'longitude'=> $long]);
```

It also seems that your code is making it into production, and as per [licence](https://github.com/teamtnt/tntsearch#ps4ware) its PS4Ware and we still haven't received any games :)
