### ISSUE TITLE
mb_strtolower() expects parameter 1 to be string, array given in Tokenizer.php line 8

### ISSUE THREAD

**Issue by Briareos17** [teamtnt/tntsearch#187]
I have followind array for indexing, it has multiple translations:

     array (
      'en' => 
      array (
        0 => 
        array (
          'title' => 'string',
          'description' => 'string',
          'meta_title' => 'string',
          'meta_description' => 'string',
          'meta_keywords' => 'string',
        ),
      ),
     'ru' => 
      array (
        0 => 
        array (
          'title' => 'string',
          'description' => 'string',
          'meta_title' => 'string',
          'meta_description' => 'string',
          'meta_keywords' => 'string',
        ),
      ),
      'id' => 1,
    )

But I have error `mb_strtolower() expects parameter 1 to be string, array given in Tokenizer.php line 8` when Indexer trying to create stems for my data, problem is `stemText($text)` argument `$text` is actualy an array with key 'ru'.

How should my data be presented for TNTSearch?

I am using Laravel 5.5 with scout and TNTSearch service provider.

**Comment by tanthammar** [comment]
I have the same problem.

**Comment by thinckx** [comment]
Check [this](https://github.com/teamtnt/laravel-scout-tntsearch-driver/) package. Use the `toSearchableArray()` method on your model to define which properties are in the index (the property should be a string, not an array).

[This](https://github.com/teamtnt/laravel-scout-tntsearch-driver/) issue might clarify things.

**Comment by casperwilkes** [comment]
I'm migrating up from an older package and ran into this issue. my solution:
```
    /**
     * TNT/Scout search array
     * @return array
     */
    public function toSearchableArray(): array {
        return $this->withoutRelations()->toArray();
    }
```
I'm using a `$with` prop for my model, so i needed to load up the model without the relations for the search object. 
This cleared the issue right up. It should probably be noted in the new documentation. The same goes for any fields that are json, they should be unset before returning this array.

**Comment by al-saloul** [comment]
I can't do anythink without this lib.

**Comment by Briareos17** [comment]
> I can't do anythink without this lib.

I decided to use own MySQL fulltext index search implementation, also Laravel 9 has MySQL scout driver from the box.

**Comment by al-saloul** [comment]
I resolved the issue, by modifying my Model and that was my fault.
