### ISSUE TITLE
Argument 1 passed to DOMNode::replaceChild() must be an instance of DOMNode, null given

### ISSUE THREAD

**Issue by simmytruong** [teamtnt/tntsearch#188]
Hi,

I encounter the issue as below when I click on the "Index content" button:
"/var/www/grav-admin/vendor/erusev/parsedown-extra/ParsedownExtra.php(473): DOMNode->replaceChild(NULL, Object(DOMElement)) 
 /var/www/grav-admin/vendor/erusev/parsedown-extra/ParsedownExtra.php(228): ParsedownExtra->processTag('<html lang="{{ ...') 
 /var/www/grav-admin/vendor/erusev/parsedown/Parsedown.php(250): ParsedownExtra->blockMarkupComplete(Array) 
 /var/www/grav-admin/vendor/erusev/parsedown/Parsedown.php(39): Parsedown->lines(Array) 
 /var/www/grav-admin/vendor/erusev/parsedown-extra/ParsedownExtra.php(46): Parsedown->text('Often, the best...') 
 /var/www/grav-admin/system/src/Grav/Common/Page/Page.php(849): ParsedownExtra->text('Often, the best...') 
 /var/www/grav-admin/system/src/Grav/Common/Page/Page.php(725): Grav\Common\Page\Page->processMarkdown() 
 /var/www/grav-admin/user/plugins/tntsearch/classes/GravTNTSearch.php(148): Grav\Common\Page\Page->content() 
 /var/www/grav-admin/user/plugins/tntsearch/classes/GravTNTSearch.php(252): Grav\Plugin\TNTSearch\GravTNTSearch::getCleanContent(Object(Grav\Common\Page\Page)) 
 /var/www/grav-admin/user/plugins/tntsearch/classes/GravConnector.php(61): Grav\Plugin\TNTSearch\GravTNTSearch->indexPageData(Object(Grav\Common\Page\Page)) "
I am using grav1.6.11. May I have an advice to sort out this issue?

Thanks,

**Comment by nticaric** [comment]
This issue isn't related to TNTSearch itself. It seems that the content forwarded to parsedown is not in the right format

**Comment by simmytruong** [comment]
Thanks for your update. But this error denies me to use the tntsearch button to reindex data. It will be always displayed the highlight error "Argument 1 passed to DOMNode::replaceChild() must be an instance of DOMNode, null given" when I click on the button. Any advice else?

**Comment by nticaric** [comment]
I guess the right place to open the ticket is https://github.com/trilbymedia/grav-plugin-tntsearch

**Comment by simmytruong** [comment]
Thanks, I will open another ticket on that mentioned link.
