### ISSUE TITLE
How to display title, category values along with id in found search results?

### ISSUE THREAD

**Issue by jun-dev** [teamtnt/tntsearch#192]
Now, the search results look like this:
```
{
  "ids": [
    2054,
    37435
  ],
  "hits": 2,
  "execution_time": "3.8171 ms"
}
```
And they should look like this:
```
{
  "ids": [
    { '"id": 2054, "title" : "Carol", "category" : 10 },
    { '"id": 37435, "title" : "Carol", "category" : 10 },
  ],
  "hits": 2,
  "execution_time": "3.8171 ms"
}
```
How do I do this best solution of all?

**Comment by stokic** [comment]
Search returns ids that match the query, then you use those ids to actually
fetch them from the database.

**Comment by jun-dev** [comment]
Can you give an example of use, how to do it faster, just I'm newbie to this?

**Comment by stokic** [comment]
Did you read the documentation or read any of the tutorials?

You literarly have to do an sql query with these ids... :)

**Comment by jun-dev** [comment]
Of course, I understand that you can do this:
`SELECT id, title, category FROM items WHERE id = 123 AND WHERE id = 125 AND WHERE id = 123 ...`
But if there are more than 10 search results, for example, then what? Doing a bulky SQL query constantly in a loop?

**Comment by stokic** [comment]
Sql has WHERE IN (listOfIds)....

Read the documentation and searching example please:

https://github.com/teamtnt/tntsearch/blob/master/README.md#searching

**Comment by jun-dev** [comment]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '[Array] ORDER BY FIELD(id, [Array])' at line 1

**Comment by stokic** [comment]
Well you obviously have a syntax error, paste your full code with query so
that we can see although it has nothing to do with this package...

**Comment by jun-dev** [comment]
Yes, maybe this is my problem in the code. I will be very grateful for your help.
	```
$this->search->selectIndex("name.index");
	//$this->search->query('SELECT id, title, status, kind, rating FROM animes;');
	$this->search->asYouType = true;
	$result = $this->search->search($query, 15);
	$result = $this->db->query("SELECT id, title, category FROM items WHERE id IN ".$result." ORDER BY FIELD(id, ".$result.");")->fetchAll();
echo var_dump($result); exit;
```
I am using Slim Framework.

**Comment by stokic** [comment]
Write the same query in some db tool or directly in mysql, when it works
copy it back to php... use some dummy ids just for the testing.

From the quick glance you have too many quotes “”...

**Comment by jun-dev** [comment]
`SELECT id, title, category FROM items WHERE id IN (2054, 37435) ORDER BY FIELD(id, 2054, 37435);`
Worked is well from Adminer.
I think it’s worth first to extract all id from the TNT Search request, then do implode (',', $ result); but this is not in the documentation. Am I thinking right?

**Comment by stokic** [comment]
You need to pass only ids to the query, that’s self evident really...

**Comment by jun-dev** [comment]
This code works, but fuzzy search does not work now. For example, I'm looking for “Керол” and there is “Кэрол” in the database, I expect to see the result, but TNTSearch does not find it.

```
        $this->search->selectIndex("name.index");
	$this->search->asYouType = true;
	$this->search->fuzziness = true;
	$result = $this->search->search($query, 15);
	$resids = implode(',', $result['ids']);
	if($resids === null || $resids == '') return $response->getBody()->write('false');
	$result = $this->db->query("SELECT id, title FROM titles WHERE id IN ($resids) ORDER BY FIELD(id, $resids);")->fetchAll();
	return $response->withJSON($result);
```

**Comment by stokic** [comment]
well for one thing, you should use russian stemmer, not the default one if you are not already...

https://github.com/teamtnt/tntsearch#creating-an-index

**Comment by jun-dev** [comment]
Don't work this in my query :(

**Comment by stokic** [comment]
Debug it, it’s basic php/mysql thing... or use stackoverflow for help on
this
