### ISSUE TITLE
Demos are offline

### ISSUE THREAD

**Issue by xf-** [teamtnt/tntsearch#197]
Tried to access the demo
![image](https://user-images.githubusercontent.com/1295633/68072643-3a7a8b80-fd88-11e9-8996-41e024711a5d.png)

**Comment by magikstm** [comment]
Just tried them today and I have the same error for the 3 demos.

http://tntsearch.tntstudio.us/
http://phpunit.tntstudio.us/
http://cities.tnt.studio/

**Comment by nticaric** [comment]
Thanks for pointing this out. We've fixed this issue.
