### ISSUE TITLE
WordPress Integration

### ISSUE THREAD

**Issue by banago** [teamtnt/tntsearch#2]
Hey @nticaric, thanks for sharing this great package. 

I have a big WordPress website that I want to improve the search of. How would I go about to integrate TNTSearch with the current website? Do I need a new DB for it or it would work fine with the current website? 

Any direction on this would help. Thanks very much.

**Comment by stokic** [comment]
Hey @banago it would work with the existing website of course, the package uses sqlite database for index creation etc. but otherwise you don't need an additional database.

What you might want to know is that we are actually working on a Wordpress plugin which will be based on this package, it should be available pretty soon, do you want us to notify you once it's done? :)

**Comment by banago** [comment]
@stokic, yes sir, sign me up. :+1:

**Comment by stokic** [comment]
@banago you'll be the first one to know about it ;)

**Comment by banago** [comment]
@stokic awesome. By the ways, I'm a long time WP developer. In case you want a hand or some beta-testing please let me know.

**Comment by banago** [comment]
Hey guys, is there any development here?

**Comment by ezequiel9** [comment]
Guys, have you got the wordpress plugin already?

**Comment by PolyPlugins** [comment]
We just finished incorporating TNTSearch into a WordPress plugin. It's called Speedy Search and it's [available for testing](https://github.com/PolyPlugins/Speedy-Search).

### Features:

- Adds a dropdown by defined selector to search form to show results
- Search through all posts fast without requiring multiple page loads
- Builds an index of all posts
- Background sync to index posts
- Ability to adjust the batch size for the initial index so smaller servers don't get overloaded
- Limit the number of results displayed
- Adds /wp-json/instant-search-for-wordpress/v1/posts endpoint to get array of post id's

### Roadmap:

- Integrate into [Admin Instant Search](https://github.com/PolyPlugins/Admin-Instant-Search)
- Add support for WooCommerce
- Add support for pages
- Add scroll to load more results
- Look into caching
- Add ability to delete index and clear complete attribute
- Add advanced search
