### ISSUE TITLE
Search with email

### ISSUE THREAD

**Issue by ideasvn** [teamtnt/tntsearch#20]
Hello!

I want when search keyword "jessika43@example.com" only return result of "jessika43@example.com" . Currently, It return results with "@example.com". How to configuration it.

**Comment by nticaric** [comment]
Try `searchBoolean`

**Comment by mandys** [comment]
Have the same issue. In Boolean can we give a regex to exclude any domain ?

**Comment by nticaric** [comment]
A slash in front of the word you want to exclude `search -exclude`. Check out the readme file for more details

**Comment by mandys** [comment]
Actually I am little confused.

When I do searchBoolean without any options and search for mandys@email.com, it searches for

[2016-08-30 07:18:10] local.INFO: array (
  0 => 'mandys',
  1 => 'email',
  2 => '&',
  3 => 'com',
  4 => '&',
  5 => '|',
)  

It gives me all results which have mandys, email, com.

But, If I try searchBoolean by passing -gmail.com, then I don't get back anything.

[2016-08-30 07:19:51] local.INFO: array (
  0 => 'mandys',
  1 => 'email',
  2 => '&',
  3 => 'com',
  4 => '&',
  5 => 'email',
  6 => '~',
  7 => '&',
  8 => 'com',
  9 => '&',
  10 => '|',
)  

In this scenario, an exact match is preferable. Do we have an option like that ?
And we can't predict all domains of the users to exclude.

**Comment by nticaric** [comment]
When you search for `mandys@email.com` isn't the first result the email you're searching for?
