### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated - PHP 7.4

### ISSUE THREAD

**Issue by vcayetano** [teamtnt/tntsearch#201]
After upgrading to PHP 7.4 I get this error In PorterStemmer.php line 396:
Array and string offset access syntax with curly braces is deprecated

    private static function doubleConsonant($str)
    {
        $c = self::$regex_consonant;

        return preg_match("#$c{2}$#", $str, $matches) && $matches[0]{0} == $matches[0]{1};
    }

**Comment by nticaric** [comment]
you should update tntsearch to the latest version

**Comment by vcayetano** [comment]
Thank You.
