### ISSUE TITLE
How to use with Laravel Vapor

### ISSUE THREAD

**Issue by lkmadushan** [teamtnt/tntsearch#203]
Since Vapor runs on AWS Lambda and it doesn't have permanent storage. How do we store indexes for searching?

**Comment by georgeboot** [comment]
I guess you could technically store the index on S3, but that won’t be performance at all.

That’s why it’s best to use other search engines like Algolia or Elasticsearch instead when you host on Vapor.

**Comment by lkmadushan** [comment]
@georgeboot thanks :) found an alternative https://github.com/meilisearch/MeiliSearch
