### ISSUE TITLE
multiple table to 1 index 

### ISSUE THREAD

**Issue by NatBLida68** [teamtnt/tntsearch#208]
i have two models with two tables  having same column row_no  i want to perform search on both on a single search for the column row_no (like scout aggregator used in algolia) the fact is i cant find any solution for this  
nb: models are not realated
i tried aggregator but but  base table not found when get() is used ,raw() works but i have no use

**Comment by Ro044** [comment]
i am too looking for this option

**Comment by NatBLida68** [comment]
NVM   i made my own custom SearchEngine
