### ISSUE TITLE
Custom Tokenizer ' Warning: Invalid argument supplied for foreach()'

### ISSUE THREAD

**Issue by Schyzophrenic** [teamtnt/tntsearch#223]
Hello,
I am trying to implement a CustomTokenizer to handle some special characters (accents for instance), but I do get an error with the custom Tokenizer mentioned in the doc.

Here is the Tokenizer:
```php
class AsciiTokenizer implements TokenizerInterface {

    public function tokenize ($text, $stopwords) {
        return preg_split("/[^\p{L}\p{N}]+/u", strtolower($text), -1, PREG_SPLIT_NO_EMPTY);
    }
}
```

I then call it with:
```php
$tnt = new TNTSearch();
$tnt->loadConfig($tntConfig); // Standard config
$indexer = $tnt->createIndex(TNTSearchService::TNT_INDEX_GAMES);
$indexer->setTokenizer(new AsciiTokenizer());
```

Without the line `$indexer->setTokenizer(new AsciiTokenizer());`, everything works fine (beside my accent issue).
When I add the custom Tokenizer I get the Issue

In TNTIndexer.php line 436:

  [ErrorException]
  Warning: Invalid argument supplied for foreach()

I am running out of ideas of what could be going wrong here... Any idea?

**Comment by nticaric** [comment]
It seems like that your tokenizer doesn't return an array

**Comment by Schyzophrenic** [comment]
Thanks @nticaric . I am actually trying to make the example in the documentation works... 

So I tried to implement the Customer Tokenizer to do the same thing as what the nomal implementation would do.

I instead created the tokenizer as:
```php
public function tokenize ($text, $stopwords) {
        $text  = mb_strtolower($text);
        $split = preg_split("/[^\p{L}\p{N}]+/u", $text, -1, PREG_SPLIT_NO_EMPTY);
        return array_diff($split, $stopwords);
    }
```

If you confirm this is the right way to do it, I am keen to improve the documentation through a PR. Let me know if you're interested (and if this is the right way to do it. That could solve the common problem raised around accentuated characters.

**Comment by Schyzophrenic** [comment]
After further investigation, I managed to make it works thanks to other issues and line by line debugging. 

Important elements:

- $stopwords has to be initiated or the search will fail. (=[] will suffice)
- The configuration should include a proper collation and charset or the UTF-8 chars will be messed up, breaking the downstream process (as we are not getting the expected charset).

This should either be a cookbook entry or a document section for this common use case. Let me know if you wish me to contribute it (which format would feet)?
