### ISSUE TITLE
Class 'TeamTNT\Scout\TNTSearchScoutServiceProvider' not found

### ISSUE THREAD

**Issue by ReubenFrimpong** [teamtnt/tntsearch#241]
In ProviderRepository.php line 208:

  Class 'TeamTNT\Scout\TNTSearchScoutServiceProvider' not found

Got this error after running composer update. My whole web app is down now because of this error and I am making any headway. Prompt response would be most appreciated

**Comment by stokic** [comment]
you shouldn't do composer update on a live app but install, after you've verified everything is ok locally...

also this is the wrong repo to ask about Scout driver https://github.com/teamtnt/laravel-scout-tntsearch-driver

did you do all of the steps of the installation https://github.com/teamtnt/laravel-scout-tntsearch-driver#installation ?

**Comment by ReubenFrimpong** [comment]
Thanks for your quick response @stokic. I would keep ur advise going forward. I have resolved the issue it was a dependency conflict between tnt search and the laravel scout tnt search driver. Error only became claer after updating my composer to the atest version.
