### ISSUE TITLE
Lack of Sqlite documentation

### ISSUE THREAD

**Issue by pierrealexaline** [teamtnt/tntsearch#248]
Documentation is very poor for Sqlite and Symfony we need to read source for understand. Please give exemple to how connect to db with sqlite. I've try different solution but nope. Impossible to have access to the dbase file in /var/, impossible to create a new indexed file. Nothing relevant about TNTsearch on google ...so please make a consistent documentation.
Another need will be a french implementation of the Stemmer algo. Thanks for your work !

**Comment by stokic** [comment]
“Doesn’t work” is not a bug/problem report.

What can’t you do? Did you try the example from the docs? Which
errors/problems you had?

Seems like you are having issues with permissions which has nothing to do
with the package but this is just a guess since you didn’t provide any clue
about anything here...

**Comment by nticaric** [comment]
Here you have the French stemmer, so it's already available in the package.

https://github.com/teamtnt/tntsearch/blob/master/src/Stemmer/FrenchStemmer.php

**Comment by pierrealexaline** [comment]
Thanks for the link ! Dear Stokic, you misunderstood, i didn't say that the application doesn't work, i hope it work great :)°, because i need it for some uses,  i just say there's a lack of documentation concerning the sqlite part and there's a lack of exemple, nothing else ! I didn't say nothing negative about your work ! i know the importance of guy that develop open source solutions like you ! ....and i just saw that you need contributors for the documentation :)° (but i can not help at this time)
thx for your work and your responses !

**Comment by stokic** [comment]
ok but what exactly is missing regarding sqlite? :) what's your suggestion?

**Comment by pierrealexaline** [comment]
i'm at work at this time i come back  later here, i'm great surprising how speed you're coming for support ! very nice thing ! :)

**Comment by pierrealexaline** [comment]
Hello there, ok i tried to install TNT search on Symfony Framework with Sqlite db, this is where i found there is a lack of documentation :
`$tnt->loadConfig([
    'driver'    => 'sqlite',
    'host'      => 'localhost',
    'database'  => 'dbname', // what next here if sqlite ???
    'username'  => 'user',// what next here if sqlite ??? Null, empty
    'password'  => 'pass',//  what next here if sqlite ???  Null, empty
    'storage'   => '/var/www/tntsearch/examples/', //  what next here if symfony ???
    'stemmer'   => \TeamTNT\TNTSearch\Stemmer\PorterStemmer::class//optional (ok i understand)
]);`
I know, my problem is not only about TNT search Sqlite but on how to integrate it with Symfony too ...
Thanks for the reply

**Comment by pierrealexaline** [comment]
Perhaps it's me that misunderstood ? is TNT search can index and search in sqlite db ? or sqlite is just used by TNT search for making indexation ... ?

**Comment by pierrealexaline** [comment]
Ok i found the how to do that ! ....not clear :)° :
```
 $tnt->loadConfig([
    'driver'    => 'sqlite',
    'host'      => 'localhost',
    'database'  => realpath('./../var/dbname.db'),
    'username'  => '',
    'password'  => '',
    'storage'   => realpath('./../var/tnt/') // set permission on it !
    'stemmer'   => \TeamTNT\TNTSearch\Stemmer\PorterStemmer::class//optional (ok i understand)
]);
```
I can play with it now ! thx
