### ISSUE TITLE
i have issue in traslate package

### ISSUE THREAD

**Issue by vahidalvandi** [teamtnt/tntsearch#252]
i need just search in current lang , i use searchable trait in another model with use       "astrotomic/laravel-translatable": "^11.5",

```
         $rows = page::whereHas('translations', function ($query) use ($q) {
                $query->search($q);
            })->take(50)->get();

```

Call to undefined method GeneaLabs\LaravelModelCaching\CachedBuilder::search()

**Comment by stokic** [comment]
This error has nothing to do with this package. Refer to laravel/scout documentation. The error message tells you where the problem is.

**Comment by vahidalvandi** [comment]
it return Call to undefined method Illuminate\Database\Eloquent\Builder::search()

**Comment by stokic** [comment]
yes, and you should fix that, your code is wrong and as I've said that error has nothing to do with this package. Put any other search package for scout with your code and you'll get the same error.

**Comment by vahidalvandi** [comment]
i need josin to parent table for check is_draft ,...

**Comment by vahidalvandi** [comment]
please help me . database structure is 
post
post_trans

serchable trait is in post_trans model and setting is in post tabel
