### ISSUE TITLE
ID as uuid type?

### ISSUE THREAD

**Issue by pnetron** [teamtnt/tntsearch#26]
I have table where ID is uuid type (string). This library doesn't work when ID type is string. Can you make it?

**Comment by paulschwarz** [comment]
Related to this, I'd like to do a federated search across multiple data sources. e.g. a "posts" and "comments" table. Wondering if it's possible to index both to the same index and then somehow identify which ones where posts and which were comments when the results come back.

**Comment by nticaric** [comment]
@paulschwarz I don't know if a simple `JOIN` would solve your issue

**Comment by nticaric** [comment]
@pnetron I think this would be possible to add without a lot of tweaking. SQLite fields can store anything no matter which type affinity they have. Have you tried to use it out of the box by simply calling your uuid column as id? Like:

```sql 
SELECT uuid as id, title, content FROM TABLE
```

**Comment by ba77osai** [comment]
Is there any update on this problem? On my setup my UUID field is named id, but from TNTSearch my doc_id response is a numeric one and not a string (so it can't lookup the row in the database).

The error on lookup is: 
    ErrorException in Collection.php line 1274:
    Undefined offset: 8947

The indexing with the cli works without problems.

**Comment by nticaric** [comment]
The document id can be anything you want. TNTSearch won't cast it to numeric. Can you try to dump the result set that you get when doing `$tnt->search('something')`? It should look something like:

```php

Array
(
    [ids] => Array
        (
            [0] => aut-in-blanditiis-repellendus-animi-11
            [1] => pariatur-voluptatem-est-quia-corrupti-sapiente-repellendus-245
            [2] => perspiciatis-libero-similique-perferendis-id-possimus-291
            [3] => velit-rerum-ratione-perferendis-sit-quas-illum-aut-286
            [4] => ipsa-saepe-nihil-repudiandae-13
            [5] => dolorem-enim-beatae-eos-possimus-200
            [6] => iure-voluptatem-sint-et-laudantium-154
            [7] => quo-numquam-dicta-aliquam-147
            [8] => architecto-quisquam-ab-sit-aut-288
            [9] => deserunt-eum-eum-deserunt-nihil-possimus-242
            [10] => libero-est-sed-doloribus-et-suscipit-18
            [11] => quo-nulla-ex-asperiores-occaecati-12
        )

    [execution time] => 24.663 ms
)
```

**Comment by ba77osai** [comment]
This is the result I get from searching (I'm using Laravel/Scout with the tntsearch driver with a doctrine model implementation)

```
array:2 [
  "ids" => array:4 [
    0 => 21049634
    1 => 642
    2 => 78825
    3 => 77627
  ]
  "execution time" => "0.602 ms"
]
```

Examples of the id coulmn values:
```
043664db-3dde-45f0-994d-48f2c64620e9
911e37c7-b4cd-4091-a78f-6ef9e997c253
82c72bb1-8ab6-4ac1-87c1-b4db5ff890fb
```

**Comment by nticaric** [comment]
Can you inspect the index file and see which values are stored there? It's a regular sqlite file and the table where you should look is `doclist` and the column is `doc_id`

**Comment by ba77osai** [comment]
`SELECT DISTINCT(doc_id) FROM doclist;`

```
73
9329
25288
526
664
25781541
188148
6336
1802767
83472587
493
14
724
8623
27060587
36
94
58
```

and some more with the same format.

The column definition (from the information my gui gives me about the table) 
doclist | doc_id | INTEGER

**Comment by nticaric** [comment]
Since the doc_id is already stored in the index as an integer I would guess that you don't have the latest version of TNTSearch installed. Try to run `composer require teamtnt/tntsearch` to update the package. Hopefully this helps

**Comment by ba77osai** [comment]
Thank you! On the newest version it works!
