### ISSUE TITLE
In what programming language is it made?

### ISSUE THREAD

**Issue by vahidalvandi** [teamtnt/tntsearch#268]
tntsearch created with C++ ?

**Comment by stokic** [comment]
All of the code is in the repo…

**Comment by nticaric** [comment]
I guess it's not hard figure it out from the repo, but here's a screenshot just in case :)

<img width="395" alt="11f82" src="https://user-images.githubusercontent.com/824840/171838871-072eb4d5-c3a6-4381-96cb-2782e0f8eeed.png">

**Comment by vahidalvandi** [comment]
but same project like meilisearch created with rust
