### ISSUE TITLE
Does it possible to reate index by array of data?

### ISSUE THREAD

**Issue by websitevirtuoso** [teamtnt/tntsearch#279]
Hello
For example I have table users that have many phones

$user = [
 'id' => 1,
 'phone' => [1236456456, 4985796792734, 23487234]
]

I am getting error mb_strtolower(): Argument #1 ($string) must be of type string, array given
I know that lib accept only primitives but maybe exist a way to index arrays? It is very simple and must have feature.

Thanks

**Comment by nticaric** [comment]
You need to do `implode` or something like that to get a string. The end result should look like:

```php
$user = [
    'id' => 1,
    'phone' => "1236456456, 4985796792734, 23487234"
]
```

**Comment by websitevirtuoso** [comment]
What about json data? Do I need to store json as a string as well?

**Comment by websitevirtuoso** [comment]
Another question. IN lib we have ability to get all locations within distance. What about polygon?
Let's say a have map of USA each state has their borders (polygon of coordinates). Does it possible to get all points (locations) inside needed polygon?
