### ISSUE TITLE
Disable searching by id

### ISSUE THREAD

**Issue by akmuhammet** [teamtnt/tntsearch#28]
It finds results when searched by ID of indexed record.
How to avoid that?

Here is how I created the index:

`$indexer = $this->tnt->createIndex('artists.index');`
`$indexer->query('SELECT id, name FROM artists');`
`$indexer->run();`

Retrieving search results:

`$this->tnt->selectIndex("artists.index");`
`$results = $this->tnt->search($keyword, 5);`
`$artists = Artist::whereIn('id', $results['ids'])->get();`

**Comment by nticaric** [comment]
Could you clarify your problem a little bit more?

**Comment by akmuhammet** [comment]
Here is the screenshot:

![screen shot 2016-08-11 at 17 45 50](https://cloud.githubusercontent.com/assets/442004/17589075/1243a49a-5fec-11e6-90c6-722024d53c55.png)

I type 10 as a search keyword, it matches artist with ID 10.
How to avoid that? I just need to be able to search by name field not by ID field.

**Comment by nticaric** [comment]
I guess the best way is to sanitize your input, if you see that it's numeric don't allow it

**Comment by akmuhammet** [comment]
Thanks very much.

I think it might be useful to make it optional in future.

**Comment by nticaric** [comment]
Yeah, it's a good idea. We'll try to fit it into the next release.

**Comment by CJLees01** [comment]
+1 for allowing the option to not index the 'id' value please. I have other numeric data column that I would like to be searchable, so sanitising my input isn't very workable.
