### ISSUE TITLE
Dynamic properties used in "TeamTNT\TNTSearch\Indexer"

### ISSUE THREAD

**Issue by menturion** [teamtnt/tntsearch#280]
Dynamic properties are used in "TeamTNT\TNTSearch\Indexer". 
These properties are ...

```
    $this->updateInfoTableStmt 
    $this->insertWordlistStmt 
    $this->selectWordlistStmt 
    $this->updateWordlistStmt 
```

This leads to a "deprecated" issue in PHP 8.2.

**Comment by ondrejznojil** [comment]
What is the state of this issue? Is anybody working on it? I could create MR fix.

**Comment by nticaric** [comment]
I you can, a MR would be great!

**Comment by nticaric** [comment]
A merge request was submitted https://github.com/teamtnt/tntsearch/pull/284/files
