### ISSUE TITLE
Depreciation : Using ${var} in strings is deprecated, use {$var} instead in PHP 8.2

### ISSUE THREAD

**Issue by pierrealexaline** [teamtnt/tntsearch#281]
You have a little depreciation in _**vendor/teamtnt/tntsearch/src/Connectors/SQLiteConnector.php**_ on line 35 (i've verified, the others connector are ok)).

Suggestion: 

It's seem that you should replace :
```
if ($path === false) {
         throw new Exception("Database (${config['database']}) does not exist.");
}
```
With that when you use PHP 8.2 :
```
if ($path === false) {
         throw new Exception("Database ({$config['database']}) does not exist.");
}
```

Thanks by advance ! and many thanks for your work !

**Comment by nticaric** [comment]
Thanks for fixing this!
