### ISSUE TITLE
SQLSTATE[HY000]: General error: 1 no such table: info

### ISSUE THREAD

**Issue by roberttolton** [teamtnt/tntsearch#29]
Hi, TNTSearch was working fine using the Facade, but I wanted to use fuzziness, so I tried the method in the docs:

```
use TeamTNT\TNTSearch\TNTSearch;

$tnt_search = new TNTSearch;

$tnt_search->selectIndex( 'notes.index' );
$tnt_search->fuzziness = true;

$search_results = $tnt_search->searchBoolean( $search, 1000 );
```

But I get an error about some info table not existing..?

```
at PDO->query('SELECT * FROM info WHERE key = 'stemmer'') in TNTSearch.php line 297
```

**Comment by nticaric** [comment]
Try to run the indexer first, it should solve your problem

**Comment by roberttolton** [comment]
I've deleted and re-created the index, but I'm still getting the error.

```
vagrant@system:/vagrant$ php artisan index:notes
Total rows 1
```

**Comment by nticaric** [comment]
You also forgot to load the config

```php
$config = ['storage' => '/path/to/storage'];
$tnt_search->loadConfig($config);

**Comment by roberttolton** [comment]
It seems a bit counter-intuitive to have to load the config again?
Since I'm already loading a config in my `services.php`.
```
'tntsearch' => [
		'driver'   => 'mysql',
		'host'     => env('DB_HOST', 'localhost'),
		'database' => env('DB_DATABASE'),
		'username' => env('DB_USERNAME'),
		'password' => env('DB_PASSWORD'),
		'storage'  => storage_path().'/tntsearch',
	],
```
I did wonder what the documentation meant by referencing that `$config` variable, I couldn't see an example definition of it. But I've now added it:
```
$tnt_search = new TNTSearch;

$config = [ 'storage' => storage_path().'/tntsearch/' ];
$tnt_search->loadConfig($config);
$tnt_search->selectIndex( 'notes.index' );
$tnt_search->fuzziness = true;

$search_results = $tnt_search->searchBoolean( $search, 1000 );
```
It seems to be happily working now.. thanks!

**Comment by nticaric** [comment]
If you're using the Facade, you don't have to load the config, it's loaded automatically for you from the services.php file. Otherwise, you need to do it manually

Via the facade you can set fuzziness like 

```php 
TNTSearch::getFacadeRoot()->fuzziness = true;
```

**Comment by roberttolton** [comment]
Oh, cool - I'll do it that way instead.

Sorry if that seems obvious from a Laravel / Symphony perspective, but I had no idea just from reading the docs. Thanks again!

**Comment by nticaric** [comment]
Great! Glad I could help.
