### ISSUE TITLE
Class 'TeamTNT\TNTSearch\Engines\Exception' not found in 'vendor/teamtnt/tntsearch/src/Engines/EngineTrait.php' line 46

### ISSUE THREAD

**Issue by dkrnl** [teamtnt/tntsearch#293]
after upgrade from v3 to v4
https://github.com/teamtnt/tntsearch/blob/master/src/Engines/EngineTrait.php#L46

**Comment by nticaric** [comment]
thanks for spotting this. its fixed now in the latest version v4.0.2
