### ISSUE TITLE
search arabic language?

### ISSUE THREAD

**Issue by mshanak** [teamtnt/tntsearch#30]
hello
i have tried to index arabic words, but the search not works 
is there any configuration for utf-8 coding?

**Comment by nticaric** [comment]
TNTSearch will work out of the box with utf-8 encoding. However, TNTSearch doesn't have an Arabic stemmer, so what you can try to do is set `$indexer->setLanguage('no');`. This will disable
the stemming process. We're welcoming the community to write an Arabic stemmer

```php
use TeamTNT\TNTSearch\TNTSearch;

$tnt = new TNTSearch;

$tnt->loadConfig([
    'driver'    => 'mysql',
    'host'      => 'localhost',
    'database'  => 'dbname',
    'username'  => 'user',
    'password'  => 'pass',
    'storage'   => '/var/www/tntsearch/examples/'
]);

$indexer = $tnt->createIndex('name.index');
$indexer->query('SELECT id, article FROM articles;');
$indexer->setLanguage('no');
$indexer->run();

```

**Comment by drashoor** [comment]
Works Fine for me, but you should put this line in 

vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php

After:

public function run()
    {
        if ($this->config['driver'] == "filesystem") {
            return $this->readDocumentsFromFileSystem();
        }

->

        $this->dbh->query("SET NAMES 'utf8'");

INDEXING:
        $indexer = TNTSearch::createIndex('book.index');
        $indexer->setLanguage('no');
        $indexer->query('SELECT id, title FROM books');
        $indexer->run();

**Comment by nticaric** [comment]
@drashoor take a look at 

https://github.com/teamtnt/tntsearch/blob/master/src/Connectors/MySqlConnector.php#L42

and you'll see that the utf8 character set is used

**Comment by drashoor** [comment]
Thanks a lot. Works Fine.


        $tnt = new TNTSearch;

        $tnt->loadConfig([
            'driver' => env('DB_CONNECTION'),
            'host' => env('DB_HOST'),
            'database' => env('DB_DATABASE'),
            'username' => env('DB_USERNAME'),
            'password' => env('DB_PASSWORD'),
            'storage' => storage_path(),
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
        ]);

        $indexer = $tnt->createIndex('book.index');
        $indexer->setLanguage('no');
        $indexer->query('SELECT id, title FROM books');
        $indexer->run();
