### ISSUE TITLE
Why add 'return'  in saveHitList function?

### ISSUE THREAD

**Issue by toohamster** [teamtnt/tntsearch#308]
https://github.com/teamtnt/tntsearch/blame/13096686f81856addcd2eabc5eb73a470be36fb4/src/Engines/SqliteEngine.php#L319

**Comment by nticaric** [comment]
the hitlist is not used in the search, so we introduced simply a return so that the index building is much faster. The hit list is only useful for "phrase search" and since we don't have it, we don't build the index with it

**Comment by toohamster** [comment]
@nticaric How do we involve the specified fields in the search?

**Comment by nticaric** [comment]
we, don't, because there is no hitlist

**Comment by msoler75** [comment]
Thanks.

In "exact phrase search" searches I use SQL FULLTEXT indexing, like:

SELECT * FROM table WHERE MATCH(text_field) AGAINST('my phrase here' IN NATURAL LANGUAGE MODE)
