### ISSUE TITLE
Index not found exception

### ISSUE THREAD

**Issue by webcrazy** [teamtnt/tntsearch#32]
Hello
~~~
IndexNotFoundException in TNTSearch.php line 65:
Index ./storage/users.index does not exist
~~~

I'm sure I have users.index file in storage directory. Am I missing something?

**Comment by nticaric** [comment]
Have you loaded the config variable where you tell the engine where to look? Can you provide some sample code that you use?

**Comment by webcrazy** [comment]
I added
~~~
SCOUT_DRIVER=tntsearch in .env file
~~~

path => config/services.php
~~~
'tntsearch' => [
        'driver'   => 'mysql',
        'host'     => env('DB_HOST', 'localhost'),
        'database' => env('DB_DATABASE'),
        'username' => env('DB_USERNAME'),
        'password' => env('DB_PASSWORD'),
        'storage'  => './storage/',
    ]
~~~

And I added index with command
~~~
php artisan index:users
~~~

And I search with this code
~~~
TNTSearch::selectIndex("users.index");
$res = TNTSearch::searchBoolean('search string', 10);
return $res;
~~~

not correct?

**Comment by nticaric** [comment]
If you are using Laravel Scout, than you don't need all of that. What you need to do is simply follow the instructions on https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/master/README.md

and the search is then done like 

```php
$res  = Post::search('something')->get();
```

**Comment by webcrazy** [comment]
Thanks but I still get this message.

~~~
InvalidArgumentException in Manager.php line 90:
Driver [tntsearch] not supported.
~~~

I added in .env file
~~~
SCOUT_DRIVER=tntsearch
~~~

**Comment by nticaric** [comment]
This is because you didn't add the service provider

```php

// config/app.php
'providers' => [
    // ...
    TeamTNT\Scout\TNTSearchScoutServiceProvider::class,
],

**Comment by nticaric** [comment]
We would also appreciate if you leave some feedback about the readme file. It seems to be confusing for people on how to install the package, so we want to improve it

**Comment by webcrazy** [comment]
Yes... It's a great package. For starting point, kind of confusing. May be integrating with laravel 5.3 full detail tutorial with example codes?

now I'm getting this one
~~~
FatalThrowableError in TNTSearchScoutServiceProvider.php line 21:
Unsupported operand types
~~~

**Comment by nticaric** [comment]
Now you're missing 

```php

'tntsearch' => [
    'storage'  => storage_path(), //place where the index files will be stored
],

in `config/scout.php`

**Comment by webcrazy** [comment]
I'm afraid I already add that one.
![screen shot 2016-08-25 at 1 45 07 am](https://cloud.githubusercontent.com/assets/5352704/17944429/b73f62f8-6a65-11e6-889a-0c30ab1d8113.png)

**Comment by nticaric** [comment]
Hmm, very strange, this is the line of code that fails

https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/master/src/TNTSearchScoutServiceProvider.php#L21

Which means some of the configuration isn't an array. Can you try to run somewhere

```php

$driver = config('database.default');
$config = config('scout.tntsearch') + config("database.connections.$driver");
dd($config);
```

and try us help to debug this

**Comment by webcrazy** [comment]
I got this one
~~~
ErrorException in web.php line 21:
Array to string conversion
~~~

**Comment by nticaric** [comment]
It seems like one of those config files is a string and one an array. Can you dump one by one, and see which one is wrong? The $driver variable should be a string, and the rest should be an array

**Comment by stokic** [comment]
so your config is obviously wrong... and possibly cached... try emptying your config cache...

btw the problem isn't related to the package at all, basic PHP/Laravel stuff...

**Comment by webcrazy** [comment]
@nticaric So sorry for the trouble and thanks a lot. I'm editing scout.php located in vendor directory.
What a stupid mistake.

Thanks @stokic.
