### ISSUE TITLE
Problem with doc_ID = 0

### ISSUE THREAD

**Issue by stevenklar** [teamtnt/tntsearch#33]
After build in your search into my user search I found a bug.

When searching for something and the unique identifier is 0
the algorythmus finds the data but the filter

https://github.com/teamtnt/tntsearch/blob/master/src/TNTSearch.php#L109

filters out the correct result. *Because key is 0 I guess.

Do you have any idea?

Work arround for me is remove the filter lines between L109 and L117.
Maybe the Collection map/filter does something wrong there?

**Comment by stevenklar** [comment]
Example:

Found Three results:

0 => User Foo
1 => User Bar
2 => User FooBar

Result after filter is 

1 => User Bar
2 => User FooBar

**Comment by nticaric** [comment]
Can you write a failing unit test for this so we can take a further look?

**Comment by nticaric** [comment]
If you're in the code, can you make a simple test by casting the key to let's say a string like:


$docs    = $docs->map(function ($doc, $key) {
           return (string) $key;
})

**Comment by stevenklar** [comment]
To write a unit test I need to extend your tests articles.sqlite.
Because there is no dataset with id 0.

Casting the $key is not working.

**Comment by stevenklar** [comment]
Add this before returning the $key works. Oh my...

`            if ($key === 0) {
                return -1;
            }`

**Comment by stevenklar** [comment]
And you know why? The Filter return $item which is 0.
Return 0 in a filter is equal to say: Filter it out!

Dunno how to fix this the better way as I wrote above.

**Comment by nticaric** [comment]
From this it seems like the problem is in the map function not filter. The core of the problem is located here

https://github.com/teamtnt/tntsearch/blob/master/src/Support/Collection.php#L52

**Comment by nticaric** [comment]
Sorry, you were right, its in the filter. Can you try to cast it there to string?

**Comment by stevenklar** [comment]
Casting `return $item` to string does not work either.
I think there is nothing to go arround the zero check.

**Comment by stevenklar** [comment]
Sorry mate for bothering you today. But glad to find bugs for you. ;)

**Comment by nticaric** [comment]
Can you try one more thing by doing 

```php
$docs    = $docs->map(function ($doc, $key) {
            return $key;
        })->filter(function ($item) use (&$counter, $numOfResults) {
            $counter++;
            if ($counter <= $numOfResults) {
                return true;
            }
        });

I think this should work, since this filter is only for counting the number of results and should work with true and false

**Comment by stevenklar** [comment]
That works. 👍

**Comment by nticaric** [comment]
Fixed, thanks for helping to debug this!

https://github.com/teamtnt/tntsearch/releases/tag/v0.8.5
