### ISSUE TITLE
dd function overrides Laravel's implementation

### ISSUE THREAD

**Issue by acasar** [teamtnt/tntsearch#36]
First, thanks a lot for creating this package! :)

I just noticed a small issue - Laravel already has a ``dd`` function defined, but there is also one defined in this package and it takes precedence over Laravel's implementation. I would like to continue using Laravel's dd, since it uses the Symfony var_dumper which results in a much more readable output.

Is there any chance that the dd function supplied with this package could be renamed since it's not really part of any core functionality?

**Comment by nticaric** [comment]
I guess we can also remove the function, it's no longer needed.  Would you mind to create a pull request?
