### ISSUE TITLE
Ignore accents

### ISSUE THREAD

**Issue by RicardoRamirezR** [teamtnt/tntsearch#43]
Hi there,

How do I tell TNTSearch to ignore accents in its indexing and searching process?

`María` becomes `maria`

Thank you.

**Comment by powolnymarcel** [comment]
In my database I have the word " français ", when I try to search for "français" the result is null....

How can I activate specials characters ?

**Comment by dbr0** [comment]
It works for me when searching for `müller` by typing `muller` but I had to change the config as

'tntsearch' => [
    'storage'  => storage_path(), //place where the index files will be stored
    'fuzziness' => env('TNTSEARCH_FUZZINESS', false),
    'fuzzy' => [
        'prefix_length' => 1, //The maximum number of terms that the fuzzy query will expand to. Defaults to 50
        'max_expansions' => 50,  //The number of initial characters which will not be “fuzzified”. This helps to reduce the number of terms which must be examined.
        'distance' => 2  //the number of one character changes that need to be made to one string to make it the same as another string
    ],
],

to change prefix_length from 2 to 1 so that it includes changes of all characters instead of first one (when set to 2 it doesn't try to change first two characters and since ü was second character it didn't work).

**Comment by powolnymarcel** [comment]
I gave up and tried Laravel 5.3 and it's working great

**Comment by dbr0** [comment]
Yes, I'm using 5.3 too.

**Comment by cbouvat** [comment]
I have the same problem, when i search "Géant" or "Geant".

**Comment by ForwardGuy** [comment]
Any new info about this feature?

**Comment by MarcosBL** [comment]
Same here, in Spanish, searching for "Malaga" gives no results if the strings contain "Málaga", it works if I search for the literal "Málaga"

**Comment by powolnymarcel** [comment]
Nothing new regarding this issue ?

**Comment by stokic** [comment]
There should be a solution for this soon (in days), we are debating the best option on how to handle it. 

In general, if you write a custom Tokenizer which replaces for example à with a and saves "cleaned" up strings in the index it'll do the trick ( so basically str_replace the strings which you want "ignored" )

**Comment by roadster31** [comment]
Some news about this issue ?

**Comment by azeos** [comment]
Any updates on this?

**Comment by prhost** [comment]
?

**Comment by stokic** [comment]
The best solution is to create a custom tokenizer (or extend the default one) and just replace characters that you need. You the do the same when searching

https://github.com/teamtnt/tntsearch#custom-tokenizer

Or if someone wants to send a PR that does this via config it would be ok, this is open source after all... :)

**Comment by Depthold-time** [comment]
https://events-culinary79.github.io/Qk2JWZH3519XyQ/



This answer might interest you
