### ISSUE TITLE
find partials of a word

### ISSUE THREAD

**Issue by sid606** [teamtnt/tntsearch#48]
Is there a way to search for a partial of a word not for the full word? For example to return  "Apple" if I search for "App" or "ppl"?

**Comment by stokic** [comment]
You'll need fuzzy search enabled, it's in the Readme:

https://github.com/teamtnt/tntsearch#fuzzy-search

**Comment by nticaric** [comment]
Have you tried `$tnt->asYouType = true` and fuzzy search? This could help you for searching words that start with your query word. If you want to search for a string that is somewhere in the middle of a word, you'll have to develop a custom solution by breaking the words into n-grams. There is a helper in the package for building 3-grams

**Comment by rkyoku** [comment]
This is an old issue, but I was having some trouble making partial-word search work. Nothing I could try with `fuzzySearch` did work, not even remotely. Hell, even `snimm` was not matching `snimmr`...

Then I found out about the `n-grams` here, and it seems to be working just fine!! (however, I limited myself to `edge-n-gram` for now, until I see a need to move to the more-broad `n-gram`)

Thanks for pointing that out!

(maybe for people not familiar with elastic search terms and definitions, you could try explaining it quickly on the main github page?)
