### ISSUE TITLE
any info about indexing?

### ISSUE THREAD

**Issue by boynet** [teamtnt/tntsearch#5]
If I understand correctly I need to re index after inserts\updated are made?

do I need to run this code on all the results or only on the updated results like
````
    $indexer = $tnt->createIndex('name.index');
    $indexer->query('SELECT id, article FROM articles where id = $last_inserted_article;');
    $indexer->run();
````

**Comment by nticaric** [comment]
Currently in this version you need to reindex your whole document collection if you made some inserts, updates or deletions. The next release of TNTSearch will support index updates and you can expect it somewhere next week.

**Comment by nticaric** [comment]
Support for dynamic indexing has been added in version 0.5.0. The readme contains more info
