### ISSUE TITLE
 Implementation of other Stemmer

### ISSUE THREAD

**Issue by robersonfaria** [teamtnt/tntsearch#51]
I would like to have a way to use another stemmer class like the one:
https://github.com/wamania/php-stemmer

It's possible?

From what I saw is fixed in the code the use of Stemmers:
$class = 'TeamTNT\\TNTSearch\\Stemmer\\' . ucfirst(strtolower($language)) . 'Stemmer';

ps:sorry about my English

Thank you

**Comment by robersonfaria** [comment]
A change that worked, but I don't think it's the right one:
File: src/TNTSearch.php
```php
public function setStemmer($stemmer = null)
{
    if(is_null($stemmer)) {
        $query = "SELECT * FROM info WHERE key = 'stemmer'";
        $docs = $this->index->query($query);
        if ($language = $docs->fetch(PDO::FETCH_ASSOC)['value']) {
            $class = 'TeamTNT\\TNTSearch\\Stemmer\\' . ucfirst(strtolower($language)) . 'Stemmer';
            $this->stemmer = new $class;
        } else {
            $this->stemmer = new PorterStemmer;
        }
    }else{
       $this->stemmer = $stemmer;
    }
}
```
My implementation:
To index:
```php
$indexer = $tnt->createIndex($this->indexName);
$indexer->query("SELECT {$fields} FROM {$table}");
$indexer->setStemmer(new Wamania\Snowball\Portuguese());
```
To search:
```php
$tnt->setStemmer(new Wamania\Snowball\Portuguese());
```

**Comment by nticaric** [comment]
Thanks for pointing that out. We made some modifications to the code to better support this.
If you mind testing it with the new version v0.9.0

The only thing that you need to do now is set the stemmer during indexing, like

```php
$indexer->setStemmer(new Wamania\Snowball\Portuguese);
```

And thats it, the search class will automatically recognize which stemmer to use.

Let us know if it works for you

**Comment by robersonfaria** [comment]
Ok, it worked very well.

Thank you very much.
