### ISSUE TITLE
Storing indexes on Amazon S3?

### ISSUE THREAD

**Issue by dragonfire1119** [teamtnt/tntsearch#53]
Could you store the indexes on Amazon S3? So multiple servers could access the same data.

**Comment by dominiquedutra** [comment]
@dragonfire1119 In theory you could sync it to S3 by modifying TNTSearch code. Haven't looked at the source to see how it deals with the index files (I believe PDO itself deals with the file directly) but you could hook into something like https://flysystem.thephpleague.com/ to keep the index file in sync with anything really. PDO should not be able to deal directly with an s3 file. It is not a disk you access, it is a file storage service. Unless you could mount the s3 drive, but an API request for each action on the file would be inevitable.

If your index is updated regularly, you would see a lot of requests to Amazon. You either have to download the index every time you want to query it (which would be stupid) or you would have to orchestrate between servers to let each other know when the s3 index has changed so the servers can fetch a fresh copy.

But why would you is what I don't understand? See my reply to https://github.com/teamtnt/tntsearch/issues/72.

There are better solutions. I recommend picking the best tool for each job.
