### ISSUE TITLE
german umlauts

### ISSUE THREAD

**Issue by klausbiedermann** [teamtnt/tntsearch#54]
Hello, i have a question regarding tntsearch and german umlauts on laravel 5.3. As i see the german umlauts i.e. ä,ö,ü,ß are not indexed. In the search form, i get no result for this. Do you have any suggestions how to config that? Thank you 
regards Klaus

**Comment by stokic** [comment]
Hi,

you can set German stemmer before executing indexing query ie. like this:

```
$indexer = $tnt->createIndex('my.index');
$indexer->setLanguage('german');
```

note that on depending how you save your data in the database you may need this as well:

`$indexer->decodeHtmlEntities();`

Hope this helps and I think we should add this to the Readme so thanks for pointing it out :)

**Comment by klausbiedermann** [comment]
Hi Sasa,

 

i dont get any search results for the german word "Büro"

 

After changing files i executed php artisan index:archives


i have the following laravel 5.3 files:

 

app\Console\Commands\IndexArchives.php:

 


    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $sql = "Select a.id, a.placenum, a.title, dept.deptshort, dept.deptlabel, doc.docutypelabel, a.description, a.storedAt, a.InOut, a.borrowedAt, a.borrowedBy, a.returnedAt, a.returnedBy, a.storagePeriode, a.created_at
        from archives a
        left join depts dept on a.deptId = dept.id
        left join docutypes doc on a.docutypeId = doc.id";

 

        $indexer = TNTSearch::createIndex('archives.index');
        
        $indexer->setLanguage('german');
        //$indexer->decodeHtmlEntities();
    Log::info('DO INDEX! ');    
        $indexer->query($sql);
        $indexer->run();
    }



 

-----------------

app\Archive.php

 

    public static function updateIndex($archive)
    {
        Log::info('update Archive Modell! ');
        TNTSearch::selectIndex("archives.index");
        $index = TNTSearch::getIndex();
        
        $index->setLanguage('german');
        //$indexer->decodeHtmlEntities();
        
        $index->update($archive->id, $archive->toArray());
    }

 

Thank you for your help

with regards

Klaus

 


Gesendet: Dienstag, 22. November 2016 um 10:14 Uhr
Von: "Sasa Tokic" <notifications@github.com>
An: teamtnt/tntsearch <tntsearch@noreply.github.com>
Cc: klausbiedermann <klaus.biedermann@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [teamtnt/tntsearch] german umlauts (#54)


Hi,

you can set German stemmer before executing indexing query ie. like this:

$indexer = $tnt->createIndex('my.index');
$indexer->setLanguage('german');


note that on depending how you save your data in the database you may need this as well:

$indexer->decodeHtmlEntities();

Hope this helps and I think we should add this to the Readme so thanks for pointing it out :)

**Comment by klausbiedermann** [comment]
now i use tntsearch with scout. It works really fantastic.
https://github.com/teamtnt/laravel-scout-tntsearch-driver

Many thanks for this great work.

**Comment by TheoJL** [comment]
Just realised that I too have this problem. 
I tried reindex with German stemmer, but it didn't seem to do anything unfortunately. 
My language is actually Swedish, but we share some chars with German. So it seems that åäö doesn't get indexed.

**Comment by stokic** [comment]
Check how your data is saved in the database, and then in the index. If you are using some kind of text editor it's possible that it doesn't save "clean" letters but escapes them... 

Since index is just a SQLite database you can peak at wordlist table and see what terms were actually indexed, let us know what you find there regarding umlauts ;)

**Comment by TheoJL** [comment]
Oh, I didn't know you could set the charset in the loadConfig object.
After setting __'charset'   => 'utf8'__ everything works. 
Thank you! :)
