### ISSUE TITLE
Is there a score per result?

### ISSUE THREAD

**Issue by t2thec** [teamtnt/tntsearch#55]
I LOVE this package. Thanks very much for putting it together.

I am using the Laravel driver and search multiple models in turn. I would like to then rank the results from all models by a score.

I presume from my digging around that this currently isn't possible? Or am I wrong?

One again, thanks for this. So simple and affective.

**Comment by fishgrind** [comment]
@t2thec 

there are some fields in the database that show this will be added. see answer here: https://github.com/teamtnt/tntsearch/issues/56

for now you could use the php similar_text function to add a weighting to the results array..

something like this:

`
foreach ($res['ids'] as $result) {

//fetch data for id from database here.

similar_text(strtolower($yourSearchQuery), strtolower($resultArray['arrayKeyToSort']), $percent);

//push data to array and include the $percent
}`

After this you can sort the array using usort

**Comment by t2thec** [comment]
Sweet. Thanks @fishgrind. Legendary work!

**Comment by fishgrind** [comment]
@t2thec no worries. Just remember similar_text is case sensitive hence the strtolower()
