### ISSUE TITLE
Using TNTSearch with F3 Jig DB

### ISSUE THREAD

**Issue by sevn** [teamtnt/tntsearch#57]
I use a php framework called Fat Free Framework and I intend to create an indexer for its own database storage called Jig. It is simple an active cursor implementation which stores data as JSON structures.

I stumbled across TNTSearch but found the documentation is lacking greatly. I've glossed over the code but I suspect it may take a few weeks to fully understand how to work with the code base.

Might anyone give me any hints on how I may tackle this project?

**Comment by nticaric** [comment]
Ok, what do you want to now?

**Comment by nticaric** [comment]
Here's the second approach:

```php
public function handle()
{
    $tnt = new TNTSearch;

    $config = [
        "storage"   => storage_path(),
    ];

    $tnt->loadConfig($config);
    $indexer = $tnt->createIndex('yourIndexName');

    $records = $this->yourMethodThatCanReadJigRowByRow();
    
   foreach($records as $record) {
       $indexer->insert(['id' => '11', 'title' => $record['title], $record['content']]);
   }
}

**Comment by sevn** [comment]
At a quick glance the second approach looks suitable.

I'd rather use Jigs mapper which allows me to walk through each row and use TNTSearch to insert what I feel is the necessary index id and data.

Basically you can think of what I'm dealing with as one very huge multidimensional array with an unknown depth. (and I'm personally storing value sets of schema.org in JSON-LD format so that makes it even more complicated.)

Could you please comment on what the insert's method argument signature is? I see it takes an array of 'type' document. I'm guessing document is a rather important concept?

**Comment by sevn** [comment]
I've implemented the second approach successfully except for two main issues.

1. The config requires a driver, it throws an error if none is specified. I've set the driver as filesystem for now.
2. Indexing takes a considerable amount of time. Up to 10 minutes for 100 rows of data containing just names. It also locks up my apache server, and happens on two seperate dev machines. And sqlite works fine as I use it every day. Not sure if its my problem or just standard for TNTSearch =\

Code follows below.
`	function index () {
		$tnt = new TNTSearch;

		$config = [
		    "storage"   => getcwd()."/db/",
		    "driver" => "filesystem"
		];

		$tnt->loadConfig($config);
		$indexer = $tnt->createIndex('testIndex');
	

		$mapper = new DB\Jig\Mapper($this->DB, "valueSets");
		foreach ($mapper->find() as $def)
		{
			$valueSet = $def->cast();

			$indexer->insert(["id"=>$valueSet["_id"], "name"=>$valueSet["details"]["name"]]);
		}
	}`

**Comment by nticaric** [comment]
Ok, lets speed it up a little bit, try to replace your `foreach`loop with:

```php
    $indexer->indexBeginTransaction();
    foreach ($mapper->find() as $jigObject) {
        $values = $jigObject->cast(); // casts to array
	$indexer->insert(["id"=>$values["_id"], "name"=>$values["details"]["name"]]);
    }
    $indexer->indexEndTransaction();
```

**Comment by sevn** [comment]
wow, that makes a significant amount of difference. From 10 minutes~ down to about 10-15 seconds. But why =\?

Also, I find that TNTSearch is indexing the id values as well? Jig stores the index keys as hashes, so they typically look like "585203233f8776.78040569".

Thank you for the prompt responses. After I create this implementation it may be a benefit to the community if I write up my own tutorial or append onto the readme file here.

**Comment by nticaric** [comment]
I'll let the `why` to be figured out by your intellectual curiosity :)

Creating a tutorial would be great. If you create one, please share it here
