### ISSUE TITLE
Please update the readme

### ISSUE THREAD

**Issue by ndabAP** [teamtnt/tntsearch#58]
Hi, I'm trying to follow the steps at the readme but there is no method run() or query() at TNTSearch(); Please fulfill the requirements to build the index. Thanks!

**Comment by stokic** [comment]
Could you explain what seems to be the problem? At what part of this process https://github.com/teamtnt/tntsearch#creating-an-index do you have a problem and what it is exactly?

**Comment by ndabAP** [comment]
I am sorry, I didn't see that createIndex() instanciates a new TNTIndexer.

It would be nice if you would help me furthermore: This is my setup:

      ```
  $tnt = new TNTSearch();

        $rootDir = $this->container->get('kernel')->getRootDir();

        $tnt->loadConfig([
            'storage' => $rootDir . '/var/search-test',
            'driver'  => 'filesystem'
        ]);

        $indexer = $tnt->createIndex('test');

        $products = $this->productHandler->findAll();

        /** @var Product $product */
        foreach ($products as $product) {
            $indexer->insert([
                'id'    => $product->getId(),
                'title' => $product->getSongTitle()
            ]);
        }

        $indexer->run();
```

I get error:

> SQLSTATE[HY000] [14] unable to open database file

**Comment by stokic** [comment]
It's a typical error described in Readme:

> Important: "storage" settings marks the folder where all of your indexes will be saved so make sure to have permission to write to this folder otherwise you might expect the following exception thrown:
> 
> [PDOException] SQLSTATE[HY000] [14] unable to open database file *

So this means that you script doesn't have write access to your folder where you are trying to save your index, it's a permission issue on the system level.

**Comment by totomtornado** [comment]
![untitled-1](https://user-images.githubusercontent.com/25587880/32362388-48a3ac84-c0ac-11e7-98ad-6f8981f25314.jpg)

I tried this but don't get how these permissions do not work.  I even set the folders to 777 to try it out and still I get the error above... Does the file need priveleges to run or the folder where the index is stored?

my error looks like this specifically and I am using composer....

> 
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /var/www/html/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php:146 Stack trace: #0 /var/www/html/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php(146): PDO->__construct('sqlite:/var/www...') #1 /var/www/html/vendor/teamtnt/tntsearch/src/TNTSearch.php(74): TeamTNT\TNTSearch\Indexer\TNTIndexer->createIndex('title.index') #2 /var/www/html/utilities/tnt_search/build-index.php(17): TeamTNT\TNTSearch\TNTSearch->createIndex('title.index') #3 {main} thrown in /var/www/html/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php on line 146

**Comment by totomtornado** [comment]
This is my indexer file:
`require  '../config.php';
require DIR_BASE . '/vendor/autoload.php';
use TeamTNT\TNTSearch\TNTSearch;

$tnt = new TNTSearch;

$tnt->loadConfig([
    'driver'    => 'mysql',
    'host'      => 'localhost',
    'database'  => 'DB',
    'username'  => 'user',
    'password'  => 'pass',
    'storage'   => '/var/www/utilities/tnt_search/indexes/'
]);

$indexer = $tnt->createIndex('title.index');
$indexer->query('SELECT ID, Title FROM Assets;');
$indexer->run();`

**Comment by totomtornado** [comment]
I found my issue... the storage path for me only needed to be "indexes"...  You can see where my build-indexes file is in the pic above.... for reference... basically I needed a relative path that references from where the index file is.... I did not think this from reading the how to...
