### ISSUE TITLE
not return exact results 

### ISSUE THREAD

**Issue by M0H3N** [teamtnt/tntsearch#59]
Hi 
thank you for this great package ... 
I tested it for a sample table with 1 million row , this is the link for download the sample database : 
http://www.sample-videos.com/sql/Sample-SQL-File-1000000rows.sql

I ran this query and it returned about 40000 rows but the package returned just 500 rows .
query : select * from user_details where first_name = 'david'

and this is my code : 
$tnt->loadConfig($config);
$tnt->selectIndex("Full");
$res = $tnt->search('david', 1000000);
var_dump($res);

what is the problem ?

**Comment by nticaric** [comment]
This should explain it 

https://github.com/teamtnt/tntsearch/blob/master/src/TNTSearch.php#L19

**Comment by M0H3N** [comment]
Ahh ... yes ... thanks a lot
