### ISSUE TITLE
Indexing relationships from Laravel?

### ISSUE THREAD

**Issue by dragonfire1119** [teamtnt/tntsearch#6]
How would you go about indexing and searching relationships from like a eloquent query?

**Comment by nticaric** [comment]
The query method during indexing supports joins. So you would write something like:

    $indexer->query('SELECT id, author_id, article, users.fullname FROM articles 
                     LEFT JOIN users ON users.id = articles.author_id;');

This would later enable you to search by users full name.
TNTSearch is actually framework agnostic so it really doesn't care about the framework. You can index any table you have in your db.

**Comment by richardblondet** [comment]
Hello guys, amazing job. 

Pardon my limited sight, I have a question, where do I place the code to specify the indexer to make the query for relationships? 

Thanks in advance!
