### ISSUE TITLE
Number of indexes

### ISSUE THREAD

**Issue by M0H3N** [teamtnt/tntsearch#62]
How to get the numbers of entry  in spesefic index ?

**Comment by nticaric** [comment]
The index file is a regular sqlite database so you can open it and look around.
The `TNTSearch` class has some methods that could also come handy like

https://github.com/teamtnt/tntsearch/blob/master/src/TNTSearch.php#L301

The indexer has also some helper methods like 

`buildDictionary` 

which can help you generate a dictionary of all the words contained in the index. The words there will be a stemmed version of a word if you used a stemmer, if not than it'll be a regular word.

**Comment by M0H3N** [comment]
thanks
