### ISSUE TITLE
Some ';' in the example code

### ISSUE THREAD

**Issue by the94air** [teamtnt/tntsearch#63]
there are some Embarrassing ; in the example query `articles;`
```
$indexer->query('SELECT id, article FROM articles;');
```

**Comment by nticaric** [comment]
It's embarrassing not to know that it's perfectly fine to close a SQL statement with a semicolon ;)

**Comment by the94air** [comment]
Sorry i didn't remember the 'semicolon' eng word. Never mind :smiley: . thanks for the info. but i don't know ???? does only 2 queries make my search fast enough?
FYI: I am not very familiar with search engines

**Comment by nticaric** [comment]
Yeah it will make your search super fast. This search package works just like a librarian does. You ask him for a book and he looks it up and brings it from a shelf, without searching the whole library.

Exactly this does `TNTSearch`, it has an inverted index where all words from your documents are stored with their positions. So when you search for the word "cat" it knows right away in which documents this word can be found.

![Inverted Index](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/SearchKitConcepts/art/inverted_index.jpg)

**Comment by the94air** [comment]
From the way that you show me,Yaa it is super fast.And if you add jQuery it is exactly like TNT

**Comment by nticaric** [comment]
Take a look at the [demo](http://tntsearch.tntstudio.us/) to see how fast it is :)

**Comment by the94air** [comment]
it is awesome. can you show me a simple  jquey code to do that? Thanks a lot

**Comment by nticaric** [comment]
It's not jQuery :D Try to play with the source code https://github.com/teamtnt/tntsearch-demo

**Comment by the94air** [comment]
I should preform action when ever i make query. I am right is that the right way to deal with tntseaech
EX
```
	$insert = $db->prepare("INSERT INTO `articles`(`title`, `article`, `slug`) VALUES (:title,:article,:slug)");

	$insert->execute([
		':title' => $title,
		':article' => $article,
		':slug' => $slug
	]);

	$article_id = $db->lastInsertId();

	$tnt->selectIndex("articles.index");

	$index = $tnt->getIndex();

	$index->insert([
		'id' => $article_id,
		'title' => $title,
		'article' => $article,
		'slug' => $slug
	]);
```

**Comment by the94air** [comment]
I am having an error when i am insert a very big text. that is causing this error `Maximum execution time of 30 seconds exceeded`

**Comment by nticaric** [comment]
Seems like you're doing everything wrong :) try to follow one of the tutorials provided on the readme page

**Comment by the94air** [comment]
I am follow the readme.md tutorials but the problem not in the code. The code is working just fine. i am asking about the Technique.

**Comment by nticaric** [comment]
So whats your question?

**Comment by the94air** [comment]
I can use the Insert index after inserting an article like i have showed you in the code before. is it the right tactic for using TNTsearch?

**Comment by the94air** [comment]
Inserting and updating is taking a lot of time causeing this error `max execute time of 30`. Should I insert long text as index in TNT search?

**Comment by nticaric** [comment]
Try this:

```php
$index->beginTransaction();
$index->insert([
		'id' => $article_id,
		'title' => $title,
		'article' => $article,
		'slug' => $slug
	]);
$index->endTransaction();
```

**Comment by the94air** [comment]
i think you meant to say 
```
$index->indexBeginTransaction();
$index->insert([
	'id' => $article_id,
	'title' => $title,
	'article' => $article,
	'slug' => $slug
]);
$index->indexEndTransaction(); 
```

**Comment by nticaric** [comment]
Yes :) Is it faster this way?

**Comment by the94air** [comment]
Yaa it is super fast. Thanks man 👍

**Comment by the94air** [comment]
I have add a repository showing how did i use TNTsearch. if you see any thing wrong just tell me :smile: 
https://github.com/the94air/TNT-search-demo

**Comment by nticaric** [comment]
Yeah, its a good start :) What I would suggest is to learn a little bit about MVC design architecture to better organize your code. After you grasp it, you could write a tutorial to share your knowledge with others

**Comment by the94air** [comment]
I always use (Slim like) structure in my projects. That was just for demo structure. i attended to use TNTSearch in web apps. And when i get more time i will consider making a tutorial
Thank you for the support (I mean 2 days support for my [issue](https://github.com/teamtnt/tntsearch/issues/63)) i really appreciate it . thanks again :smiley:
