### ISSUE TITLE
search on  primary key problem 

### ISSUE THREAD

**Issue by M0H3N** [teamtnt/tntsearch#65]
I make a index by this code :   $indexer->query("SELECT id, publish_status FROM posts"); 

publish_status is a Boolean  field.

this code returns rows that have publish_status = 1 and row which have Id = 1 : 
       $tnt->search(1, 100);

what is the problem ? I dont want to search on primary key of table .

**Comment by reals79** [comment]
Same problem.
How it solve?

**Comment by M0H3N** [comment]
I couldn't find any solution

**Comment by ultrono** [comment]
Same issue here. I'm searching products codes that contain a combination of numbers and text.

When searching for numbers TNTSearch will rank a query matching the document id higher. For example, if I have the following index: 

```
[
    [
        'id' => 20865,
        'name' => 'xzy-abc'
    ],
    [
        'id' => 519845,
        'name' => 'MT-MOTOR_20865_06'
    ],
]; 
```

If a user searches for the term "20865" the 'MT-MOTOR_20865_06' document would ideally be displayed first. TNT search appears to favor exact document id matches. Thus in this search, 'xzy-abc' is displayed first, which obviously doesn't make sense.

Does anyone have any advice for searching product codes with a mixture of letters and numbers. As I have a large (>1 million) data set I get the latter pretty frequently.

Thanks

**Comment by ultrono** [comment]
As this screen is ranked highly in Google and I needed to use TNT outside Laravel, the solution is `excludePrimaryKey()` i.e.

```php
/** @var \TeamTNT\TNTSearch\Engines\SqliteEngine $indexer */
$indexer = $service->createIndex(indexName: 'products.index');
$indexer->excludePrimaryKey(); // <----
$indexer->query('...');
$indexer->run();
```

@stokic Assuming that method should be included on the https://github.com/teamtnt/tntsearch/blob/master/src/Contracts/EngineContract.php engine interface too?
