### ISSUE TITLE
Boolean Search returns results in two formats

### ISSUE THREAD

**Issue by pkissman** [teamtnt/tntsearch#66]
If I do a boolean search such as "robert -frost"  records are returned in this format, with an array of ids in square brackets:
{"ids":["10.031","11.003","11.004","62.001"],"hits":40,"execution time":"164.6152 ms"}

Whereas if I search on the same index with "robert or frost", records are returned in this format, as an associative array with curly braces:
{"ids":{"0":"217.002","1":"218.173"},"hits":43,"execution time":"4.812 ms"}

I wonder why that is.

**Comment by nticaric** [comment]
Are you running the result set through json_encode or something like that?

**Comment by pkissman** [comment]
Ok.  Now I’m embarrassed.  I thought I was seeing the disparate results that I reported coming straight out of your search functions.  But of course you are quite correct; I do encode the results into json.  So, I need to examine what is coming directly of my database query’s before that point and dig into json_encode a bit to see why the encoding is different.

pjk
