### ISSUE TITLE
loadConfig error

### ISSUE THREAD

**Issue by dalip123** [teamtnt/tntsearch#67]
[Symfony\Component\Debug\Exception\FatalErrorException]                     
  Call to undefined method TeamTNT\TNTSearch\Facades\TNTSearch::loadConfig()

**Comment by nticaric** [comment]
You shouldn't use the facade since it's deprecated. There is a scout driver available for easy
integration with laravel

https://github.com/teamtnt/laravel-scout-tntsearch-driver
