### ISSUE TITLE
Question on automatic indexing

### ISSUE THREAD

**Issue by rishabgarg** [teamtnt/tntsearch#68]
I was able to setup tntsearch successfully but wasn't able to get automatic indexing work. 

I was following this article http://tnt.studio/blog/searching-for-bobby-fisher-with-laravel-5 but I realized that the latest version of TnTSearch is different from what has been described in the article.

Are we still supposed to have the 4 static functions in our model class to get the automatic indexing work or is it a different process now.

**Comment by nticaric** [comment]
If you want to automate everything try to use the scout driver

https://github.com/teamtnt/laravel-scout-tntsearch-driver

and here's a tutorial on how to set it up

https://laravel-news.com/tntsearch-with-laravel-scout
