### ISSUE TITLE
City search, weighing by match relevance and population

### ISSUE THREAD

**Issue by bridgeport** [teamtnt/tntsearch#69]
First, thanks for providing this package.

I'm trying to implement a city search across tens of thousands of records. I have a city name, state name, and population field.

I'd like to have the results take into account population so that the biggest is weighted towards the top. For instance, if there was a search performed for "Miami" I'd obviously want "Miami, FL" to have priority over "Miami, OH".

So the search would have to
1) Rank by relevance and use the population field (in descending order/biggest to smallest) as a ranking factor, and
2) Exclude the population field from its content search query, which may not really even be necessary since it's numeric anyway and would probably not match anything.

Is this possible in TNT?

Thanks.

**Comment by nticaric** [comment]
Maybe you'll be interested in this tutorial 

http://tnt.studio/blog/did-you-mean-functionality-with-laravel-scout

and this demo page http://cities.tnt.studio/

The trick is to return the results by relevance and then to sort the result set by population. The code from the demo site that does exactly this is:

https://github.com/teamtnt/cities/blob/master/app/Http/Controllers/CityController.php.php#L59

**Comment by nticaric** [comment]
If you have longitude and latitude for each city, you can also implement a geo search

https://github.com/teamtnt/tntsearch#geo-search
