### ISSUE TITLE
How to run TNT with about 14 servers

### ISSUE THREAD

**Issue by arunjoseph** [teamtnt/tntsearch#72]
I have about 14 servers hosting php and laravel how can I store the index and where can I store ? Using sqlite ?

**Comment by nticaric** [comment]
Someone might help you if you elaborate your question a little bit. It really depends on your setup.
If each server runs a laravel instance you can have one index for each one, so in total 14 indexes.
Or you might want one server handle the search, and others to connect to it via REST, this would than basically work like elastic search.

**Comment by Jaspaul** [comment]
@nticaric Is there any preferred strategy to synchronize the index across multiple app servers? For instance I want any of the 14 servers to be able to handle the incoming search, but I don't want each of them doing the work to maintain an index. I've been looking into rsync to do this, but I'm curious if there's another recommended approach.

**Comment by dominiquedutra** [comment]
@Jaspaul @arunjoseph If I had the necessity to synchronize the index between servers I would look into another solution. IMO relying on Rsync to keep your index consistent is asking for trouble.

TNTSearch is great and I am implementing it on one project of mine and so far it's working really good and it's really easy to setup, but if I were you I would look into either tossing a buck for Algolia (I know it's expensive depending on the project's  income, I've debated myself to use or not), or I would setup Solr or ElasticSearch.

I believe it is easier to learn and setup another piece of software than it is to keep indexes in sync using rsync.

As a last resort, I would pick one of the 14 servers, install Lumen and TNTSearch and expose this single server as an indexer/searcher API. This would take some relying on Laravels model events but it should work in the end.

**Comment by alexsegura** [comment]
> As a last resort, I would pick one of the 14 servers, install Lumen and TNTSearch and expose this single server as an indexer/searcher API.

Actually, I don't see this as the last resort, but the best solution 🙂 
TNTSearch is great because it allows to add search with an existing PHP stack, but this problem of replication can be a blocker. I implemented it, but I'm now switching to [Sonic](https://github.com/valeriansaliou/sonic), because of this. 

Honestly, it would be great to ship TNTSearch as an API. Even better, packaged in a Docker image.

**Comment by stokic** [comment]
There will be tntsearch with replication soon ;)
