### ISSUE TITLE
indexing sql view

### ISSUE THREAD

**Issue by physio** [teamtnt/tntsearch#79]
good morning, sorry for my orrible english.
I use this package with several models and all works fine.
I have created a model where the table attribute is not a sql table, but a sql view. 
How i can maually update this model's indexing when some connected tables'update?

reguards

**Comment by sankam-nikolya** [comment]
https://dev.mysql.com/doc/refman/5.7/en/view-updatability.html

> Earlier discussion in this section pointed out that a view is not insertable if not all columns are simple column references (for example, if it contains columns that are expressions or composite expressions). Although such a view is not insertable, it can be updatable if you update only columns that are not expressions
