### ISSUE TITLE
s/Hihglighter/Highlighter/

### ISSUE THREAD

**Issue by jakejohns** [teamtnt/tntsearch#8]
Is this a typo? or am I confused?
Shouldn't `TeamTNT\TNTSearch\Support\Hihglighter` be `TeamTNT\TNTSearch\Support\Highlighter`

**Comment by nticaric** [comment]
@jakejohns yes, it's a typo :) checkout v0.4.0, should be ok there. Thanks for spotting it!

**Comment by jakejohns** [comment]
cool. sorry i didnt just send a PR. wasn't sure if i was confused or not.
