### ISSUE TITLE
Search not working with leading apostrophes

### ISSUE THREAD

**Issue by dnsimmons** [teamtnt/tntsearch#80]
It appears that the search does not work properly with words that have apostrophes in the starting portion of the word. I have replicated the same issue many times over using different wording with the same patterns:

Problem:
Searching for term like OLearys DOES NOT yield results for the actual text O'Learys.
Searching for term like Gibsons DOES yield results for the actual text Gibson's

This is a "fuzzy" search by the way and is basically the example provided in the README.

Any ideas?

Thanks in advance.

**Comment by nticaric** [comment]
To solve this particular problem you could extend the current tokenizer that does not split words by an apostrophe. The current [tokenizer](https://github.com/teamtnt/tntsearch/blob/master/src/Support/Tokenizer.php#L9) breaks the word `O'Learys` into two parts `O` and `Learys` which we call tokens so the fuzziness is applied to each token and doesn't give any results
