### ISSUE TITLE
Stop words?

### ISSUE THREAD

**Issue by TheDailySpank** [teamtnt/tntsearch#83]
Just wondering if there are plans on adding an optional stop words functionality. Words such as "the", "and", "to", "of", "a"... 

I'm using the hack below, with a longer list, for now.

**Tokenizer.php**
```php
namespace TeamTNT\TNTSearch\Support;

class Tokenizer implements TokenizerInterface
{
    /**
     * @param  $text
     * @return mixed
     */
    public function tokenize($text)
    {
        $stopwords = ["the", "and", "to", "of", "a", "in", "i", "is", "on"];
        $text  = mb_strtolower($text);
        $split = preg_split("/[^\p{L}\p{N}]+/u", $text, -1, PREG_SPLIT_NO_EMPTY);
        $tokenized   = array_diff($split, $stopwords);
        return $tokenized;
    }
}

**Comment by ultrono** [comment]
Isn;t the reason the class has a method to set a custom Tokenizer via the ```setTokenizer()``` method?

**Comment by nticaric** [comment]
The indexer has also a property called `$stopWords` where you simply put an array of stopwords
