### ISSUE TITLE
info | Handling i18n

### ISSUE THREAD

**Issue by akazorg** [teamtnt/tntsearch#85]
Hi. Congrats for your work!

I've used tntsearch but there's something not clear about multi languages.
Would you kindly provide some extra info on this?

I am curious about:
- do you create a separate Index per language?
- do we require a Stemmer per each language?

Thank you.
🚀

**Comment by akazorg** [comment]
Is this question hard to answer? (almost 4 months have passed)

I really would like to know what is the best approach on this.

Can you PLEASE answer?
Thank you.!

**Comment by stokic** [comment]
Hi Bruno,

Yes create multiple indexes for each languages.

Also different stemmers for different languages if possible for the best
results.

**Comment by akazorg** [comment]
Hi Sasa, thank you for the reply. I wanted to make sure.
