### ISSUE TITLE
Destroy the PDO sqlite connection after each run

### ISSUE THREAD

**Issue by dominiquedutra** [teamtnt/tntsearch#88]
Hey,

O hooked TNTSearch into one of my apps and its working as intended. Vhala!

I have a bunch of tests using Codeception. There must be close to a thousand unit tests.

It seems the PDO connection used by TNTSearch is not closed after each test. When running all of Codeception tests it runs in a single process and after a couple hundred tests, it throws a Too Many Connections error.

"Fail  SQLSTATE[08004] [1040] Too many connections".

I believe the proper solution would be to destroy the PDO connection after each ->search() / ->searchBoolean(). This problem would also happen in most tests suites, considering Codeception heavily relies on PHPUnit.

Tried setting the $this->dbh variable on TeamTNT\TNTSearch\TNTSearch to null after the search is done but it does not seem to help.

I am not familiar with PDO having always worked with some sort of abstraction layer. Looking for guidance so I can get a PR going.

Thanks.

**Comment by dominiquedutra** [comment]
May be a problem elsewhere. Too many Laravel Eloquent connections for updating the relationships.

Im looking into it. Was just looking for some advise regarding TNTSearch connection.

This `Tried setting the $this->dbh variable on TeamTNT\TNTSearch\TNTSearch to null after the search is done but it does not seem to help.` should've fixed TNTSearch side.

**Comment by nticaric** [comment]
Take a look here https://github.com/laravel/framework/issues/18471. It seems to be the same issue

**Comment by nticaric** [comment]
About nulling it on TNTSearch, it wouldn't have any effect because sqlite doesn't work that way.
It uses read/write lock for the entire db file which means if another process wants to read/write to it, it has to wait. Sqlite has no concurrency and always only ONE connections at a time open

**Comment by dominiquedutra** [comment]
Thanks! I am looking into it and will get back.
