### ISSUE TITLE
Demo and Docs links broken

### ISSUE THREAD

**Issue by rhukster** [teamtnt/tntsearch#90]
I've been reading your great blog post: http://tnt.studio/blog/solving-the-search-problem-with-laravel-and-tntsearch

But the Demo and Documentation links just point to a "namecheap" landing page.  Is there anyway to get access to those demo and docs?

Broken:

* http://phpunit.tntstudio.us/
* http://tntsearch.tntstudio.us/

Cheers

**Comment by nticaric** [comment]
Thanks for pointing that out! We fixed one of the links, still one to go. I guess @stokic will take care of this when he gets a minute.

**Comment by rhukster** [comment]
Thanks @nticaric that will help :)

**Comment by nticaric** [comment]
Closing this one since the links are up & running again.
