### ISSUE TITLE
Custom Connector

### ISSUE THREAD

**Issue by rhukster** [teamtnt/tntsearch#91]
I'm developing a plugin for Grav CMS (https://github.com/getgrav/grav) using this sweet library, however, i'm finding it a bit tricky to properly integrate Grav with TNTSearch.

There's quite a few places in `TNTIndexer` and TNTSearch that looks for what is basically a static list of connectors and drivers.  I'm getting around this right now by creating my own `GravIndexer` class that extends the `TNTIndexer` and overrides the `run()` method to load the `Grav::pages` object and iterate over the pages and store the `$page->content()`. 

This is working OK (as long as I still store the driver as `filesystem`), but it would be really nice If I were able to **register** a custom connector and use that to define how things should be indexed and retrieved.  Is this something that is on the roadmap?

**Comment by nticaric** [comment]
I am not very familiar with Grav CMS yet, I understand that it's a flat file system. Would you mind explaining how the pages/articles/posts are saved to the filesystem. Is it only one file, multiple files, a sqlite database or something else. Does each article/post have an unique ID? Maybe we could write a custom connector for Grav if necessary

**Comment by rhukster** [comment]
You can see the rough initial commit here:

https://github.com/trilbymedia/grav-plugin-tnt-search

Basically I have two CLI commands that you run with 

```
bin/plugin tnt-search index
```

and to test query:

```
bin/plugin tnt-search query foo
```

To answer your question, Grav is a flat file CMS so files are stored as markdown with frontmatter, and are cached/compiled at run time to render as HTML like a traditional CMS.  It's not a static generator, so you can't simply point it at existing static HTML files.  You have to retrieve the pages from Grav and iterate over them and then request the `Page::title()` and `Page::content()` similar to how you would if you were iterating over a database table.  

The unique id is the page's route within Grav (`Page::route()`) which is effectively the URL of the page.

You can see in the repo, how i'm indexing Grav from the CLI and and storing the info in a similar fashion to the filesystem connector, however, being a dynamic CMS, I would love to be able to index title, taxonomy, and other attributes.

BTW. You can test this if you like by grabbing the blog skeleton package (https://getgrav.org/download/skeletons/blog-site/1.1.1) extracting it to your webroot, then cloning the grav-plugin-tnt-search plugin into `user/plugins/tnt-search`.

No other installation necessary :)

**Comment by rhukster** [comment]
BTW, relevant files are:

https://github.com/trilbymedia/grav-plugin-tnt-search/blob/develop/cli/IndexerCommand.php
https://github.com/trilbymedia/grav-plugin-tnt-search/blob/develop/classes/GravIndexer.php
https://github.com/trilbymedia/grav-plugin-tnt-search/blob/develop/cli/QueryCommand.php

**Comment by nticaric** [comment]
What about this approach... in your `IndexerCommand` you would have:

```php
    private function doIndex()
    {
        include __DIR__.'/../vendor/autoload.php';
        error_reporting(1);

        $data_path = Grav::instance()['locator']->findResource('user://data', true).'/tnt-search';

        if (!file_exists($data_path)) {
            mkdir($data_path);
        }

        $tnt = new TNTSearch;

        $tnt->loadConfig([
            'driver'  => 'sqlite',
            'storage' => $data_path
        ]);
        $tnt->setDatabaseHandle(new GravConnector);
        $indexer = $tnt->createIndex('grav.index');
        $indexer->run();

    }
```

Next, you would create a `GravConnector`

```php
class GravConnector extends \PDO
{
    public function __construct()
    {}

    public function query($query)
    {
        $grav = Grav::instance();
        $grav['debugger']->enabled(false);
        $grav['twig']->init();
        /** @var Pages $pages */
        $pages = Grav::instance()['pages'];
        $pages->init();
        $collection = $pages->all();
        //Drop unpublished and unroutable pages
        $collection->published()->routable();

        $results = [];
        foreach ($collection as $page) {
            $counter++;
            $route = $page->route();
            try {
                $results[] = [
                    'id'      => $counter,
                    'name'    => $page->title(),
                    'content' => strip_tags($page->content())
                ];
            } catch (\Exception $e) {
                $this->info("Skipped $counter $route");
                continue;
            }
        }

        return new GravResultObject($results);
    }
}
```

And at last `GravResultObject`

```php
class GravResultObject
{
    public function __construct($items)
    {
        $this->counter = 0;
        $this->items = $items;
    }
    public function fetch($options)
    {
        return $this->items[$this->counter++];
    }
}
```

**Comment by nticaric** [comment]
Here's my whole file. It seems to work

```php
<?php
namespace Grav\Plugin\Console;

use Grav\Common\Grav;
use Grav\Console\ConsoleCommand;
use TeamTNT\TNTSearch\TNTSearch;

/**
 * Class IndexerCommand
 *
 * @package Grav\Plugin\Console
 */
class IndexerCommand extends ConsoleCommand
{
    /**
     * @var array
     */
    protected $options = [];
    /**
     * @var array
     */
    protected $colors = [
        'DEBUG'     => 'green',
        'INFO'      => 'cyan',
        'NOTICE'    => 'yellow',
        'WARNING'   => 'yellow',
        'ERROR'     => 'red',
        'CRITICAL'  => 'red',
        'ALERT'     => 'red',
        'EMERGENCY' => 'magenta'
    ];

    /**
     *
     */
    protected function configure()
    {
        $this
            ->setName("index")
            ->setDescription("TNTSearch Indexer")
            ->setHelp('The <info>index command</info> re-indexes the search engine');
    }

    /**
     * @return int|null|void
     */
    protected function serve()
    {

        $this->output->writeln('');
        $this->output->writeln('<magenta>Re-indexing Search</magenta>');
        $this->output->writeln('');

        $this->doIndex();
        $this->output->writeln('Done.');
    }

    private function doIndex()
    {
        include __DIR__.'/../vendor/autoload.php';
        error_reporting(1);

        $data_path = Grav::instance()['locator']->findResource('user://data', true).'/tnt-search';

        if (!file_exists($data_path)) {
            mkdir($data_path);
        }

        $tnt = new TNTSearch;

        $tnt->loadConfig([
            'driver'  => 'sqlite',
            'storage' => $data_path
        ]);
        $tnt->setDatabaseHandle(new GravConnector);
        $indexer = $tnt->createIndex('grav.index');
        $indexer->run();

    }
}

class GravConnector extends \PDO
{
    public function __construct()
    {}

    public function query($query)
    {
        $grav = Grav::instance();
        $grav['debugger']->enabled(false);
        $grav['twig']->init();
        /** @var Pages $pages */
        $pages = Grav::instance()['pages'];
        $pages->init();
        $collection = $pages->all();
        //Drop unpublished and unroutable pages
        $collection->published()->routable();

        $results = [];
        foreach ($collection as $page) {
            $counter++;
            $route = $page->route();
            try {
                $results[] = [
                    'id'      => $counter,
                    'name'    => $page->title(),
                    'content' => strip_tags($page->content())
                ];
            } catch (\Exception $e) {
                $this->info("Skipped $counter $route");
                continue;
            }
        }

        return new GravResultObject($results);
    }
}

class GravResultObject
{
    public function __construct($items)
    {
        $this->counter = 0;
        $this->items   = $items;
    }
    public function fetch($options)
    {
        return $this->items[$this->counter++];
    }
}

```

**Comment by nticaric** [comment]
Searching also does work with a little modification

![Query Results](http://tntstudio.hr:8081/images/28d3b.png)

**Comment by rhukster** [comment]
OK, great i've updated the plugin with your changes and tweaked the search to respond with the JSON that includes the 'relevant content'.  Seems to work just as before, and nice and snappy :)

I have a few other questions:

1. How do retreive the total number of documents indexed? This was inserted into 'info' table with the filesystem driver, but doesn't seem to be for sqlite.

2. If i wanted to add taxonomy or any other field (author etc), I would simply update that `$results` array in the `GravConnector` object?  TNTSearch will automatically know to index and search in any field I specify in there?

Thanks for your help so far!

**Comment by nticaric** [comment]
The total number of indexed documents should still be there, try this:

![](http://tntstudio.hr:8081/images/d1ea8.png)

Make sure that the array doesn't go out of bounds in

https://github.com/trilbymedia/grav-plugin-tntsearch/blob/develop/classes/GravResultObject.php#L16

This would cause an error and the total number of documents wouldn't be updated at the end. So first check if it's set, otherwise return false/null/0

**Comment by nticaric** [comment]
Regarding your second question, yes, thats correct. Something like this

```php
$results[] = [
     'id'          => $route,
     'name'    => $page->title(),
    'author'   => $page->author(),
     'content' => strip_tags($page->content())
];
```

So the index will contain everything with what you feed it - author, taxonomies, tags etc. any kind of text data

**Comment by rhukster** [comment]
Awesome thanks!
