### ISSUE TITLE
TNTSearch Grav Plugin Released!

### ISSUE THREAD

**Issue by rhukster** [teamtnt/tntsearch#92]
Should be showing up in Grav GPM shortly, but you can see the details on the GitHub repo: https://github.com/trilbymedia/grav-plugin-tntsearch

Thanks to @nticaric for all your help making this possible.

**Comment by nticaric** [comment]
Glad I could help!!

**Comment by nticaric** [comment]
@rhukster is there a download counter of the plugin? would be interesting to know how many people download it

**Comment by rhukster** [comment]
There is not a visible counter, although we plan on enabling download counts on the getgrav.org site pretty soon.
