### ISSUE TITLE
Getting "Undefined variable: searchBoolean " ErrorException.

### ISSUE THREAD

**Issue by D-sense** [teamtnt/tntsearch#96]
Hello devs,

I was getting an error with the below method in TNTSearchEngine.php. 

     `protected function performSearch(Builder $builder, array $options = [])
    {
        $index = $builder->index ?: $builder->model->searchableAs();
        $limit = $builder->limit ?: 10000;
        $this->tnt->selectIndex("{$index}.index");

        $this->builder = $builder;
        $this->tnt->asYouType = $builder->model->asYouType ?: false;

        if ($builder->callback) {
            return call_user_func(
                $builder->callback,
                $this->tnt,
                $builder->query,
                $options
            );
        }
        if ($this->tnt->config['searchBoolean']) {
            return $this->tnt->searchBoolean($builder->query, $limit);
        } else {
            return $this->tnt->search($builder->query, $limit);
        }
    }`

However, the code seems completely different from the same version I downloaded a few weeks ago. See below the same method:

    `protected function performSearch(Builder $builder, array $options = [])
    {
        $index = $builder->index ?: $builder->model->searchableAs();
        $limit = $builder->limit ?: 10000;
        $this->tnt->selectIndex("{$index}.index");

        $this->builder = $builder;
        $this->tnt->asYouType = $builder->model->asYouType ?: false;

        if ($builder->callback) {
            return call_user_func(
                $builder->callback,
                $this->tnt,
                $builder->query,
                $options
            );
        }
     
        return $this->tnt->search($builder->query, $limit);
    }`

To be precise, using the former method in my laravel app, I am receiving ErrorException Undefined index: searchBoolean. The only solution I coould come up with is falling back on the latter mathod. Please, could anyone explain this?
Thank you.

**Comment by nticaric** [comment]
It seems like you are using the scout package and are missing 

```php
'searchBoolean' => env('TNTSEARCH_BOOLEAN', false),
```
from the config file

**Comment by D-sense** [comment]
Yes, you are very correct. That solves the issue. Thank you.
