### ISSUE TITLE
Greatly lacking PHP-DOC :(

### ISSUE THREAD

**Issue by lgXenos** [teamtnt/tntsearch#98]
![tntsearchnondoc](https://user-images.githubusercontent.com/14957311/30058940-a802c2ae-9245-11e7-8b73-91fb5bb7b648.png)

IDE feel to crazy ) Wtf the method? Wtf the class? )))
Or disable of the php-doc - your ingenious plan of world domination?)

**Comment by stokic** [comment]
How about submitting a pull request, it'll just take you a few minutes :)

**Comment by lgXenos** [comment]
I'm take 5.
;)

Ok, after my first step in yours search, I'm trying make some basical php-doc

**Comment by stokic** [comment]
Great, that would be awesome ;)

**Comment by lgXenos** [comment]
https://github.com/teamtnt/tntsearch/pull/99

**Comment by lgXenos** [comment]
Also I'm edit type of variable at loadConfig to array, because at some line we see use this variable as array
```
public function loadConfig(array $config){
....
$this->config['storage'] = rtrim($this->config['storage'], '/').'/';
```
